/*
 * STACKIT IaaS API
 * This API is deprecated. It will be retired on 01.03.2027. Please use the STACKIT IaaS API V2 instead.
 *
 * The version of the OpenAPI document: 1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.v1api.model;

import cloud.stackit.sdk.iaas.v1api.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Object that represents the request body for a network create. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class CreateNetworkPayload {
	public static final String SERIALIZED_NAME_ADDRESS_FAMILY = "addressFamily";

	@SerializedName(SERIALIZED_NAME_ADDRESS_FAMILY)
	@javax.annotation.Nullable private CreateNetworkAddressFamily addressFamily;

	public static final String SERIALIZED_NAME_DHCP = "dhcp";

	@SerializedName(SERIALIZED_NAME_DHCP)
	@javax.annotation.Nullable private Boolean dhcp = true;

	public static final String SERIALIZED_NAME_LABELS = "labels";

	@SerializedName(SERIALIZED_NAME_LABELS)
	@javax.annotation.Nullable private Object labels;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	@javax.annotation.Nonnull
	private String name;

	public static final String SERIALIZED_NAME_ROUTED = "routed";

	@SerializedName(SERIALIZED_NAME_ROUTED)
	@javax.annotation.Nullable private Boolean routed;

	public CreateNetworkPayload() {}

	public CreateNetworkPayload addressFamily(
			@javax.annotation.Nullable CreateNetworkAddressFamily addressFamily) {
		this.addressFamily = addressFamily;
		return this;
	}

	/**
	 * Get addressFamily
	 *
	 * @return addressFamily
	 */
	@javax.annotation.Nullable public CreateNetworkAddressFamily getAddressFamily() {
		return addressFamily;
	}

	public void setAddressFamily(
			@javax.annotation.Nullable CreateNetworkAddressFamily addressFamily) {
		this.addressFamily = addressFamily;
	}

	public CreateNetworkPayload dhcp(@javax.annotation.Nullable Boolean dhcp) {
		this.dhcp = dhcp;
		return this;
	}

	/**
	 * Enable or disable DHCP for a network.
	 *
	 * @return dhcp
	 */
	@javax.annotation.Nullable public Boolean getDhcp() {
		return dhcp;
	}

	public void setDhcp(@javax.annotation.Nullable Boolean dhcp) {
		this.dhcp = dhcp;
	}

	public CreateNetworkPayload labels(@javax.annotation.Nullable Object labels) {
		this.labels = labels;
		return this;
	}

	/**
	 * Object that represents the labels of an object. Regex for keys:
	 * &#x60;^(?&#x3D;.{1,63}$)([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$&#x60;. Regex for values:
	 * &#x60;^(?&#x3D;.{0,63}$)(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])*$&#x60;. Providing a
	 * &#x60;null&#x60; value for a key will remove that key. The &#x60;stackit-&#x60; prefix is
	 * reserved and cannot be used for Keys.
	 *
	 * @return labels
	 */
	@javax.annotation.Nullable public Object getLabels() {
		return labels;
	}

	public void setLabels(@javax.annotation.Nullable Object labels) {
		this.labels = labels;
	}

	public CreateNetworkPayload name(@javax.annotation.Nonnull String name) {
		this.name = name;
		return this;
	}

	/**
	 * The name for a General Object. Matches Names and also UUIDs.
	 *
	 * @return name
	 */
	@javax.annotation.Nonnull
	public String getName() {
		return name;
	}

	public void setName(@javax.annotation.Nonnull String name) {
		this.name = name;
	}

	public CreateNetworkPayload routed(@javax.annotation.Nullable Boolean routed) {
		this.routed = routed;
		return this;
	}

	/**
	 * Shows if the network is routed and therefore accessible from other networks.
	 *
	 * @return routed
	 */
	@javax.annotation.Nullable public Boolean getRouted() {
		return routed;
	}

	public void setRouted(@javax.annotation.Nullable Boolean routed) {
		this.routed = routed;
	}

	/**
	 * A container for additional, undeclared properties. This is a holder for any undeclared
	 * properties as specified with the 'additionalProperties' keyword in the OAS document.
	 */
	private Map<String, Object> additionalProperties;

	/**
	 * Set the additional (undeclared) property with the specified name and value. If the property
	 * does not already exist, create it otherwise replace it.
	 *
	 * @param key name of the property
	 * @param value value of the property
	 * @return the CreateNetworkPayload instance itself
	 */
	public CreateNetworkPayload putAdditionalProperty(String key, Object value) {
		if (this.additionalProperties == null) {
			this.additionalProperties = new HashMap<String, Object>();
		}
		this.additionalProperties.put(key, value);
		return this;
	}

	/**
	 * Return the additional (undeclared) property.
	 *
	 * @return a map of objects
	 */
	public Map<String, Object> getAdditionalProperties() {
		return additionalProperties;
	}

	/**
	 * Return the additional (undeclared) property with the specified name.
	 *
	 * @param key name of the property
	 * @return an object
	 */
	public Object getAdditionalProperty(String key) {
		if (this.additionalProperties == null) {
			return null;
		}
		return this.additionalProperties.get(key);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CreateNetworkPayload createNetworkPayload = (CreateNetworkPayload) o;
		return Objects.equals(this.addressFamily, createNetworkPayload.addressFamily)
				&& Objects.equals(this.dhcp, createNetworkPayload.dhcp)
				&& Objects.equals(this.labels, createNetworkPayload.labels)
				&& Objects.equals(this.name, createNetworkPayload.name)
				&& Objects.equals(this.routed, createNetworkPayload.routed)
				&& Objects.equals(
						this.additionalProperties, createNetworkPayload.additionalProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(addressFamily, dhcp, labels, name, routed, additionalProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CreateNetworkPayload {\n");
		sb.append("    addressFamily: ").append(toIndentedString(addressFamily)).append("\n");
		sb.append("    dhcp: ").append(toIndentedString(dhcp)).append("\n");
		sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    routed: ").append(toIndentedString(routed)).append("\n");
		sb.append("    additionalProperties: ")
				.append(toIndentedString(additionalProperties))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields =
				new HashSet<String>(
						Arrays.asList("addressFamily", "dhcp", "labels", "name", "routed"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(Arrays.asList("name"));
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to CreateNetworkPayload
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!CreateNetworkPayload.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in CreateNetworkPayload is not found in the empty JSON string",
								CreateNetworkPayload.openapiRequiredFields.toString()));
			}
		}

		// check to make sure all required properties/fields are present in the JSON string
		for (String requiredField : CreateNetworkPayload.openapiRequiredFields) {
			if (jsonElement.getAsJsonObject().get(requiredField) == null) {
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field `%s` is not found in the JSON string: %s",
								requiredField,
								jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// validate the optional field `addressFamily`
		if (jsonObj.get("addressFamily") != null && !jsonObj.get("addressFamily").isJsonNull()) {
			CreateNetworkAddressFamily.validateJsonElement(jsonObj.get("addressFamily"));
		}
		if (!jsonObj.get("name").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `name` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("name").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!CreateNetworkPayload.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'CreateNetworkPayload' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<CreateNetworkPayload> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(CreateNetworkPayload.class));

			return (TypeAdapter<T>)
					new TypeAdapter<CreateNetworkPayload>() {
						@Override
						public void write(JsonWriter out, CreateNetworkPayload value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							obj.remove("additionalProperties");
							// serialize additional properties
							if (value.getAdditionalProperties() != null) {
								for (Map.Entry<String, Object> entry :
										value.getAdditionalProperties().entrySet()) {
									if (entry.getValue() instanceof String)
										obj.addProperty(entry.getKey(), (String) entry.getValue());
									else if (entry.getValue() instanceof Number)
										obj.addProperty(entry.getKey(), (Number) entry.getValue());
									else if (entry.getValue() instanceof Boolean)
										obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
									else if (entry.getValue() instanceof Character)
										obj.addProperty(
												entry.getKey(), (Character) entry.getValue());
									else {
										JsonElement jsonElement = gson.toJsonTree(entry.getValue());
										if (jsonElement.isJsonArray()) {
											obj.add(entry.getKey(), jsonElement.getAsJsonArray());
										} else {
											obj.add(entry.getKey(), jsonElement.getAsJsonObject());
										}
									}
								}
							}
							elementAdapter.write(out, obj);
						}

						@Override
						public CreateNetworkPayload read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							JsonObject jsonObj = jsonElement.getAsJsonObject();
							// store additional fields in the deserialized instance
							CreateNetworkPayload instance = thisAdapter.fromJsonTree(jsonObj);
							for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
								if (!openapiFields.contains(entry.getKey())) {
									if (entry.getValue().isJsonPrimitive()) { // primitive type
										if (entry.getValue().getAsJsonPrimitive().isString())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsString());
										else if (entry.getValue().getAsJsonPrimitive().isNumber())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsNumber());
										else if (entry.getValue().getAsJsonPrimitive().isBoolean())
											instance.putAdditionalProperty(
													entry.getKey(),
													entry.getValue().getAsBoolean());
										else
											throw new IllegalArgumentException(
													String.format(
															java.util.Locale.ROOT,
															"The field `%s` has unknown primitive type. Value: %s",
															entry.getKey(),
															entry.getValue().toString()));
									} else if (entry.getValue().isJsonArray()) {
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), List.class));
									} else { // JSON object
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), HashMap.class));
									}
								}
							}
							return instance;
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of CreateNetworkPayload given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of CreateNetworkPayload
	 * @throws IOException if the JSON string is invalid with respect to CreateNetworkPayload
	 */
	public static CreateNetworkPayload fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, CreateNetworkPayload.class);
	}

	/**
	 * Convert an instance of CreateNetworkPayload to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
