/*
 * STACKIT IaaS API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.v2api.model;

import cloud.stackit.sdk.iaas.v2api.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

/** Object that represents a resource as part of a request. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class RequestResource {
	public static final String SERIALIZED_NAME_ID = "id";

	@SerializedName(SERIALIZED_NAME_ID)
	@javax.annotation.Nonnull
	private UUID id;

	public static final String SERIALIZED_NAME_STATUS = "status";

	@SerializedName(SERIALIZED_NAME_STATUS)
	@javax.annotation.Nonnull
	private String status;

	public static final String SERIALIZED_NAME_TYPE = "type";

	@SerializedName(SERIALIZED_NAME_TYPE)
	@javax.annotation.Nonnull
	private String type;

	public RequestResource() {}

	public RequestResource id(@javax.annotation.Nonnull UUID id) {
		this.id = id;
		return this;
	}

	/**
	 * Universally Unique Identifier (UUID).
	 *
	 * @return id
	 */
	@javax.annotation.Nonnull
	public UUID getId() {
		return id;
	}

	public void setId(@javax.annotation.Nonnull UUID id) {
		this.id = id;
	}

	public RequestResource status(@javax.annotation.Nonnull String status) {
		this.status = status;
		return this;
	}

	/**
	 * The state of a resource object. Possible values: &#x60;CREATING&#x60;, &#x60;CREATED&#x60;,
	 * &#x60;DELETING&#x60;, &#x60;DELETED&#x60;, &#x60;FAILED&#x60;, &#x60;UPDATED&#x60;,
	 * &#x60;UPDATING&#x60;.
	 *
	 * @return status
	 */
	@javax.annotation.Nonnull
	public String getStatus() {
		return status;
	}

	public void setStatus(@javax.annotation.Nonnull String status) {
		this.status = status;
	}

	public RequestResource type(@javax.annotation.Nonnull String type) {
		this.type = type;
		return this;
	}

	/**
	 * Object that represents a resource type. Possible values: &#x60;BACKUP&#x60;,
	 * &#x60;IMAGE&#x60;, &#x60;NETWORK&#x60;, &#x60;NETWORKAREA&#x60;, &#x60;NIC&#x60;,
	 * &#x60;PROJECT&#x60;, &#x60;ROUTE&#x60;, &#x60;SERVER&#x60;, &#x60;SERVICEACCOUNT&#x60;,
	 * &#x60;SNAPSHOT&#x60;, &#x60;VIRTUALIP&#x60;, &#x60;VOLUME&#x60;.
	 *
	 * @return type
	 */
	@javax.annotation.Nonnull
	public String getType() {
		return type;
	}

	public void setType(@javax.annotation.Nonnull String type) {
		this.type = type;
	}

	/**
	 * A container for additional, undeclared properties. This is a holder for any undeclared
	 * properties as specified with the 'additionalProperties' keyword in the OAS document.
	 */
	private Map<String, Object> additionalProperties;

	/**
	 * Set the additional (undeclared) property with the specified name and value. If the property
	 * does not already exist, create it otherwise replace it.
	 *
	 * @param key name of the property
	 * @param value value of the property
	 * @return the RequestResource instance itself
	 */
	public RequestResource putAdditionalProperty(String key, Object value) {
		if (this.additionalProperties == null) {
			this.additionalProperties = new HashMap<String, Object>();
		}
		this.additionalProperties.put(key, value);
		return this;
	}

	/**
	 * Return the additional (undeclared) property.
	 *
	 * @return a map of objects
	 */
	public Map<String, Object> getAdditionalProperties() {
		return additionalProperties;
	}

	/**
	 * Return the additional (undeclared) property with the specified name.
	 *
	 * @param key name of the property
	 * @return an object
	 */
	public Object getAdditionalProperty(String key) {
		if (this.additionalProperties == null) {
			return null;
		}
		return this.additionalProperties.get(key);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RequestResource requestResource = (RequestResource) o;
		return Objects.equals(this.id, requestResource.id)
				&& Objects.equals(this.status, requestResource.status)
				&& Objects.equals(this.type, requestResource.type)
				&& Objects.equals(this.additionalProperties, requestResource.additionalProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, status, type, additionalProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RequestResource {\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    additionalProperties: ")
				.append(toIndentedString(additionalProperties))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("id", "status", "type"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "status", "type"));
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to RequestResource
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!RequestResource.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in RequestResource is not found in the empty JSON string",
								RequestResource.openapiRequiredFields.toString()));
			}
		}

		// check to make sure all required properties/fields are present in the JSON string
		for (String requiredField : RequestResource.openapiRequiredFields) {
			if (jsonElement.getAsJsonObject().get(requiredField) == null) {
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field `%s` is not found in the JSON string: %s",
								requiredField,
								jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		if (!jsonObj.get("id").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `id` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("id").toString()));
		}
		if (!jsonObj.get("status").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `status` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("status").toString()));
		}
		if (!jsonObj.get("type").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `type` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("type").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!RequestResource.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'RequestResource' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<RequestResource> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(RequestResource.class));

			return (TypeAdapter<T>)
					new TypeAdapter<RequestResource>() {
						@Override
						public void write(JsonWriter out, RequestResource value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							obj.remove("additionalProperties");
							// serialize additional properties
							if (value.getAdditionalProperties() != null) {
								for (Map.Entry<String, Object> entry :
										value.getAdditionalProperties().entrySet()) {
									if (entry.getValue() instanceof String)
										obj.addProperty(entry.getKey(), (String) entry.getValue());
									else if (entry.getValue() instanceof Number)
										obj.addProperty(entry.getKey(), (Number) entry.getValue());
									else if (entry.getValue() instanceof Boolean)
										obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
									else if (entry.getValue() instanceof Character)
										obj.addProperty(
												entry.getKey(), (Character) entry.getValue());
									else {
										JsonElement jsonElement = gson.toJsonTree(entry.getValue());
										if (jsonElement.isJsonArray()) {
											obj.add(entry.getKey(), jsonElement.getAsJsonArray());
										} else {
											obj.add(entry.getKey(), jsonElement.getAsJsonObject());
										}
									}
								}
							}
							elementAdapter.write(out, obj);
						}

						@Override
						public RequestResource read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							JsonObject jsonObj = jsonElement.getAsJsonObject();
							// store additional fields in the deserialized instance
							RequestResource instance = thisAdapter.fromJsonTree(jsonObj);
							for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
								if (!openapiFields.contains(entry.getKey())) {
									if (entry.getValue().isJsonPrimitive()) { // primitive type
										if (entry.getValue().getAsJsonPrimitive().isString())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsString());
										else if (entry.getValue().getAsJsonPrimitive().isNumber())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsNumber());
										else if (entry.getValue().getAsJsonPrimitive().isBoolean())
											instance.putAdditionalProperty(
													entry.getKey(),
													entry.getValue().getAsBoolean());
										else
											throw new IllegalArgumentException(
													String.format(
															java.util.Locale.ROOT,
															"The field `%s` has unknown primitive type. Value: %s",
															entry.getKey(),
															entry.getValue().toString()));
									} else if (entry.getValue().isJsonArray()) {
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), List.class));
									} else { // JSON object
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), HashMap.class));
									}
								}
							}
							return instance;
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of RequestResource given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of RequestResource
	 * @throws IOException if the JSON string is invalid with respect to RequestResource
	 */
	public static RequestResource fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, RequestResource.class);
	}

	/**
	 * Convert an instance of RequestResource to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
