/*
 * STACKIT Application Load Balancer API
 * This API offers an interface to provision and manage Application Load Balancers in your STACKIT project.This solution offers modern L7 load balancing. Current features include TLS, path and prefix based routing aswell as routing based on headers, query parameters and keeping connections persistent with cookies and web sockets.  For each Application Load Balancer provided, two VMs are deployed in your STACKIT project and are subject to fees.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.alb.model;

import cloud.stackit.sdk.alb.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

/** GetQuotaResponse */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class GetQuotaResponse {
	public static final String SERIALIZED_NAME_MAX_CREDENTIALS = "maxCredentials";

	@SerializedName(SERIALIZED_NAME_MAX_CREDENTIALS)
	@javax.annotation.Nullable private Integer maxCredentials;

	public static final String SERIALIZED_NAME_MAX_LOAD_BALANCERS = "maxLoadBalancers";

	@SerializedName(SERIALIZED_NAME_MAX_LOAD_BALANCERS)
	@javax.annotation.Nullable private Integer maxLoadBalancers;

	public static final String SERIALIZED_NAME_PROJECT_ID = "projectId";

	@SerializedName(SERIALIZED_NAME_PROJECT_ID)
	@javax.annotation.Nullable private UUID projectId;

	public static final String SERIALIZED_NAME_REGION = "region";

	@SerializedName(SERIALIZED_NAME_REGION)
	@javax.annotation.Nullable private String region;

	public static final String SERIALIZED_NAME_USED_CREDENTIALS = "usedCredentials";

	@SerializedName(SERIALIZED_NAME_USED_CREDENTIALS)
	@javax.annotation.Nullable private Integer usedCredentials;

	public static final String SERIALIZED_NAME_USED_LOAD_BALANCERS = "usedLoadBalancers";

	@SerializedName(SERIALIZED_NAME_USED_LOAD_BALANCERS)
	@javax.annotation.Nullable private Integer usedLoadBalancers;

	public GetQuotaResponse() {}

	public GetQuotaResponse(UUID projectId, String region) {
		this();
		this.projectId = projectId;
		this.region = region;
	}

	public GetQuotaResponse maxCredentials(@javax.annotation.Nullable Integer maxCredentials) {
		this.maxCredentials = maxCredentials;
		return this;
	}

	/**
	 * The maximum number of observability credentials that can be stored in this project. minimum:
	 * -1 maximum: 999
	 *
	 * @return maxCredentials
	 */
	@javax.annotation.Nullable public Integer getMaxCredentials() {
		return maxCredentials;
	}

	public void setMaxCredentials(@javax.annotation.Nullable Integer maxCredentials) {
		this.maxCredentials = maxCredentials;
	}

	public GetQuotaResponse maxLoadBalancers(@javax.annotation.Nullable Integer maxLoadBalancers) {
		this.maxLoadBalancers = maxLoadBalancers;
		return this;
	}

	/**
	 * The maximum number of load balancing servers in this project. minimum: -1 maximum: 999
	 *
	 * @return maxLoadBalancers
	 */
	@javax.annotation.Nullable public Integer getMaxLoadBalancers() {
		return maxLoadBalancers;
	}

	public void setMaxLoadBalancers(@javax.annotation.Nullable Integer maxLoadBalancers) {
		this.maxLoadBalancers = maxLoadBalancers;
	}

	/**
	 * Project identifier
	 *
	 * @return projectId
	 */
	@javax.annotation.Nullable public UUID getProjectId() {
		return projectId;
	}

	/**
	 * Region
	 *
	 * @return region
	 */
	@javax.annotation.Nullable public String getRegion() {
		return region;
	}

	public GetQuotaResponse usedCredentials(@javax.annotation.Nullable Integer usedCredentials) {
		this.usedCredentials = usedCredentials;
		return this;
	}

	/**
	 * The number of observability credentials that are currently existing in this project. minimum:
	 * -1 maximum: 1000000
	 *
	 * @return usedCredentials
	 */
	@javax.annotation.Nullable public Integer getUsedCredentials() {
		return usedCredentials;
	}

	public void setUsedCredentials(@javax.annotation.Nullable Integer usedCredentials) {
		this.usedCredentials = usedCredentials;
	}

	public GetQuotaResponse usedLoadBalancers(
			@javax.annotation.Nullable Integer usedLoadBalancers) {
		this.usedLoadBalancers = usedLoadBalancers;
		return this;
	}

	/**
	 * The number of load balancing servers that are currently existing in this project. minimum: -1
	 * maximum: 1000000
	 *
	 * @return usedLoadBalancers
	 */
	@javax.annotation.Nullable public Integer getUsedLoadBalancers() {
		return usedLoadBalancers;
	}

	public void setUsedLoadBalancers(@javax.annotation.Nullable Integer usedLoadBalancers) {
		this.usedLoadBalancers = usedLoadBalancers;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GetQuotaResponse getQuotaResponse = (GetQuotaResponse) o;
		return Objects.equals(this.maxCredentials, getQuotaResponse.maxCredentials)
				&& Objects.equals(this.maxLoadBalancers, getQuotaResponse.maxLoadBalancers)
				&& Objects.equals(this.projectId, getQuotaResponse.projectId)
				&& Objects.equals(this.region, getQuotaResponse.region)
				&& Objects.equals(this.usedCredentials, getQuotaResponse.usedCredentials)
				&& Objects.equals(this.usedLoadBalancers, getQuotaResponse.usedLoadBalancers);
	}

	@Override
	public int hashCode() {
		return Objects.hash(
				maxCredentials,
				maxLoadBalancers,
				projectId,
				region,
				usedCredentials,
				usedLoadBalancers);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetQuotaResponse {\n");
		sb.append("    maxCredentials: ").append(toIndentedString(maxCredentials)).append("\n");
		sb.append("    maxLoadBalancers: ").append(toIndentedString(maxLoadBalancers)).append("\n");
		sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
		sb.append("    region: ").append(toIndentedString(region)).append("\n");
		sb.append("    usedCredentials: ").append(toIndentedString(usedCredentials)).append("\n");
		sb.append("    usedLoadBalancers: ")
				.append(toIndentedString(usedLoadBalancers))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields =
				new HashSet<String>(
						Arrays.asList(
								"maxCredentials",
								"maxLoadBalancers",
								"projectId",
								"region",
								"usedCredentials",
								"usedLoadBalancers"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to GetQuotaResponse
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!GetQuotaResponse.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in GetQuotaResponse is not found in the empty JSON string",
								GetQuotaResponse.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!GetQuotaResponse.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `GetQuotaResponse` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		if ((jsonObj.get("projectId") != null && !jsonObj.get("projectId").isJsonNull())
				&& !jsonObj.get("projectId").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							"Expected the field `projectId` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("projectId").toString()));
		}
		if ((jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull())
				&& !jsonObj.get("region").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							"Expected the field `region` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("region").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!GetQuotaResponse.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'GetQuotaResponse' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<GetQuotaResponse> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(GetQuotaResponse.class));

			return (TypeAdapter<T>)
					new TypeAdapter<GetQuotaResponse>() {
						@Override
						public void write(JsonWriter out, GetQuotaResponse value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public GetQuotaResponse read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of GetQuotaResponse given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of GetQuotaResponse
	 * @throws IOException if the JSON string is invalid with respect to GetQuotaResponse
	 */
	public static GetQuotaResponse fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, GetQuotaResponse.class);
	}

	/**
	 * Convert an instance of GetQuotaResponse to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
