/*
 * STACKIT Application Load Balancer API
 * This API offers an interface to provision and manage Application Load Balancers in your STACKIT project.This solution offers modern L7 load balancing. Current features include TLS, path and prefix based routing aswell as routing based on headers, query parameters and keeping connections persistent with cookies and web sockets.  For each Application Load Balancer provided, two VMs are deployed in your STACKIT project and are subject to fees.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.alb.model;

import cloud.stackit.sdk.alb.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Options for the HTTP health checking. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class HttpHealthChecks {
	public static final String SERIALIZED_NAME_OK_STATUSES = "okStatuses";

	@SerializedName(SERIALIZED_NAME_OK_STATUSES)
	@javax.annotation.Nullable private List<String> okStatuses = new ArrayList<>();

	public static final String SERIALIZED_NAME_PATH = "path";

	@SerializedName(SERIALIZED_NAME_PATH)
	@javax.annotation.Nullable private String path;

	public HttpHealthChecks() {}

	public HttpHealthChecks okStatuses(@javax.annotation.Nullable List<String> okStatuses) {
		this.okStatuses = okStatuses;
		return this;
	}

	public HttpHealthChecks addOkStatusesItem(String okStatusesItem) {
		if (this.okStatuses == null) {
			this.okStatuses = new ArrayList<>();
		}
		this.okStatuses.add(okStatusesItem);
		return this;
	}

	/**
	 * List of HTTP status codes that indicate a healthy response
	 *
	 * @return okStatuses
	 */
	@javax.annotation.Nullable public List<String> getOkStatuses() {
		return okStatuses;
	}

	public void setOkStatuses(@javax.annotation.Nullable List<String> okStatuses) {
		this.okStatuses = okStatuses;
	}

	public HttpHealthChecks path(@javax.annotation.Nullable String path) {
		this.path = path;
		return this;
	}

	/**
	 * Path to send the health check request to
	 *
	 * @return path
	 */
	@javax.annotation.Nullable public String getPath() {
		return path;
	}

	public void setPath(@javax.annotation.Nullable String path) {
		this.path = path;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		HttpHealthChecks httpHealthChecks = (HttpHealthChecks) o;
		return Objects.equals(this.okStatuses, httpHealthChecks.okStatuses)
				&& Objects.equals(this.path, httpHealthChecks.path);
	}

	@Override
	public int hashCode() {
		return Objects.hash(okStatuses, path);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class HttpHealthChecks {\n");
		sb.append("    okStatuses: ").append(toIndentedString(okStatuses)).append("\n");
		sb.append("    path: ").append(toIndentedString(path)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("okStatuses", "path"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to HttpHealthChecks
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!HttpHealthChecks.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in HttpHealthChecks is not found in the empty JSON string",
								HttpHealthChecks.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!HttpHealthChecks.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The field `%s` in the JSON string is not defined in the `HttpHealthChecks` properties. JSON: %s",
								entry.getKey(),
								jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// ensure the optional json data is an array if present
		if (jsonObj.get("okStatuses") != null
				&& !jsonObj.get("okStatuses").isJsonNull()
				&& !jsonObj.get("okStatuses").isJsonArray()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `okStatuses` to be an array in the JSON string but got `%s`",
							jsonObj.get("okStatuses").toString()));
		}
		if ((jsonObj.get("path") != null && !jsonObj.get("path").isJsonNull())
				&& !jsonObj.get("path").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `path` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("path").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!HttpHealthChecks.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'HttpHealthChecks' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<HttpHealthChecks> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(HttpHealthChecks.class));

			return (TypeAdapter<T>)
					new TypeAdapter<HttpHealthChecks>() {
						@Override
						public void write(JsonWriter out, HttpHealthChecks value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public HttpHealthChecks read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of HttpHealthChecks given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of HttpHealthChecks
	 * @throws IOException if the JSON string is invalid with respect to HttpHealthChecks
	 */
	public static HttpHealthChecks fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, HttpHealthChecks.class);
	}

	/**
	 * Convert an instance of HttpHealthChecks to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
