/*
 * STACKIT Application Load Balancer API
 * This API offers an interface to provision and manage Application Load Balancers in your STACKIT project.This solution offers modern L7 load balancing. Current features include TLS, path and prefix based routing aswell as routing based on headers, query parameters and keeping connections persistent with cookies and web sockets.  For each Application Load Balancer provided, two VMs are deployed in your STACKIT project and are subject to fees.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.alb.model;

import cloud.stackit.sdk.alb.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** ListCredentialsResponse */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class ListCredentialsResponse {
	public static final String SERIALIZED_NAME_CREDENTIALS = "credentials";

	@SerializedName(SERIALIZED_NAME_CREDENTIALS)
	@javax.annotation.Nullable private List<CredentialsResponse> credentials = new ArrayList<>();

	public ListCredentialsResponse() {}

	public ListCredentialsResponse credentials(
			@javax.annotation.Nullable List<CredentialsResponse> credentials) {
		this.credentials = credentials;
		return this;
	}

	public ListCredentialsResponse addCredentialsItem(CredentialsResponse credentialsItem) {
		if (this.credentials == null) {
			this.credentials = new ArrayList<>();
		}
		this.credentials.add(credentialsItem);
		return this;
	}

	/**
	 * Get credentials
	 *
	 * @return credentials
	 */
	@javax.annotation.Nullable public List<CredentialsResponse> getCredentials() {
		return credentials;
	}

	public void setCredentials(@javax.annotation.Nullable List<CredentialsResponse> credentials) {
		this.credentials = credentials;
	}

	/**
	 * A container for additional, undeclared properties. This is a holder for any undeclared
	 * properties as specified with the 'additionalProperties' keyword in the OAS document.
	 */
	private Map<String, Object> additionalProperties;

	/**
	 * Set the additional (undeclared) property with the specified name and value. If the property
	 * does not already exist, create it otherwise replace it.
	 *
	 * @param key name of the property
	 * @param value value of the property
	 * @return the ListCredentialsResponse instance itself
	 */
	public ListCredentialsResponse putAdditionalProperty(String key, Object value) {
		if (this.additionalProperties == null) {
			this.additionalProperties = new HashMap<String, Object>();
		}
		this.additionalProperties.put(key, value);
		return this;
	}

	/**
	 * Return the additional (undeclared) property.
	 *
	 * @return a map of objects
	 */
	public Map<String, Object> getAdditionalProperties() {
		return additionalProperties;
	}

	/**
	 * Return the additional (undeclared) property with the specified name.
	 *
	 * @param key name of the property
	 * @return an object
	 */
	public Object getAdditionalProperty(String key) {
		if (this.additionalProperties == null) {
			return null;
		}
		return this.additionalProperties.get(key);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ListCredentialsResponse listCredentialsResponse = (ListCredentialsResponse) o;
		return Objects.equals(this.credentials, listCredentialsResponse.credentials)
				&& Objects.equals(
						this.additionalProperties, listCredentialsResponse.additionalProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(credentials, additionalProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ListCredentialsResponse {\n");
		sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
		sb.append("    additionalProperties: ")
				.append(toIndentedString(additionalProperties))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("credentials"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to ListCredentialsResponse
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!ListCredentialsResponse.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in ListCredentialsResponse is not found in the empty JSON string",
								ListCredentialsResponse.openapiRequiredFields.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		if (jsonObj.get("credentials") != null && !jsonObj.get("credentials").isJsonNull()) {
			JsonArray jsonArraycredentials = jsonObj.getAsJsonArray("credentials");
			if (jsonArraycredentials != null) {
				// ensure the json data is an array
				if (!jsonObj.get("credentials").isJsonArray()) {
					throw new IllegalArgumentException(
							String.format(
									java.util.Locale.ROOT,
									"Expected the field `credentials` to be an array in the JSON string but got `%s`",
									jsonObj.get("credentials").toString()));
				}

				// validate the optional field `credentials` (array)
				for (int i = 0; i < jsonArraycredentials.size(); i++) {
					CredentialsResponse.validateJsonElement(jsonArraycredentials.get(i));
				}
				;
			}
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!ListCredentialsResponse.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'ListCredentialsResponse' and its
				// subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<ListCredentialsResponse> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(ListCredentialsResponse.class));

			return (TypeAdapter<T>)
					new TypeAdapter<ListCredentialsResponse>() {
						@Override
						public void write(JsonWriter out, ListCredentialsResponse value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							obj.remove("additionalProperties");
							// serialize additional properties
							if (value.getAdditionalProperties() != null) {
								for (Map.Entry<String, Object> entry :
										value.getAdditionalProperties().entrySet()) {
									if (entry.getValue() instanceof String)
										obj.addProperty(entry.getKey(), (String) entry.getValue());
									else if (entry.getValue() instanceof Number)
										obj.addProperty(entry.getKey(), (Number) entry.getValue());
									else if (entry.getValue() instanceof Boolean)
										obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
									else if (entry.getValue() instanceof Character)
										obj.addProperty(
												entry.getKey(), (Character) entry.getValue());
									else {
										JsonElement jsonElement = gson.toJsonTree(entry.getValue());
										if (jsonElement.isJsonArray()) {
											obj.add(entry.getKey(), jsonElement.getAsJsonArray());
										} else {
											obj.add(entry.getKey(), jsonElement.getAsJsonObject());
										}
									}
								}
							}
							elementAdapter.write(out, obj);
						}

						@Override
						public ListCredentialsResponse read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							JsonObject jsonObj = jsonElement.getAsJsonObject();
							// store additional fields in the deserialized instance
							ListCredentialsResponse instance = thisAdapter.fromJsonTree(jsonObj);
							for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
								if (!openapiFields.contains(entry.getKey())) {
									if (entry.getValue().isJsonPrimitive()) { // primitive type
										if (entry.getValue().getAsJsonPrimitive().isString())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsString());
										else if (entry.getValue().getAsJsonPrimitive().isNumber())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsNumber());
										else if (entry.getValue().getAsJsonPrimitive().isBoolean())
											instance.putAdditionalProperty(
													entry.getKey(),
													entry.getValue().getAsBoolean());
										else
											throw new IllegalArgumentException(
													String.format(
															java.util.Locale.ROOT,
															"The field `%s` has unknown primitive type. Value: %s",
															entry.getKey(),
															entry.getValue().toString()));
									} else if (entry.getValue().isJsonArray()) {
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), List.class));
									} else { // JSON object
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), HashMap.class));
									}
								}
							}
							return instance;
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of ListCredentialsResponse given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of ListCredentialsResponse
	 * @throws IOException if the JSON string is invalid with respect to ListCredentialsResponse
	 */
	public static ListCredentialsResponse fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, ListCredentialsResponse.class);
	}

	/**
	 * Convert an instance of ListCredentialsResponse to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
