/*
 * STACKIT Application Load Balancer API
 * This API offers an interface to provision and manage Application Load Balancers in your STACKIT project.This solution offers modern L7 load balancing. Current features include TLS, path and prefix based routing aswell as routing based on headers, query parameters and keeping connections persistent with cookies and web sockets.  For each Application Load Balancer provided, two VMs are deployed in your STACKIT project and are subject to fees.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.alb.model;

import cloud.stackit.sdk.alb.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Defines any optional functionality you want to have enabled on your Application Load Balancer.
 */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class LoadBalancerOptions {
	public static final String SERIALIZED_NAME_ACCESS_CONTROL = "accessControl";

	@SerializedName(SERIALIZED_NAME_ACCESS_CONTROL)
	@javax.annotation.Nullable private LoadbalancerOptionAccessControl accessControl;

	public static final String SERIALIZED_NAME_EPHEMERAL_ADDRESS = "ephemeralAddress";

	@SerializedName(SERIALIZED_NAME_EPHEMERAL_ADDRESS)
	@javax.annotation.Nullable private Boolean ephemeralAddress;

	public static final String SERIALIZED_NAME_OBSERVABILITY = "observability";

	@SerializedName(SERIALIZED_NAME_OBSERVABILITY)
	@javax.annotation.Nullable private LoadbalancerOptionObservability observability;

	public static final String SERIALIZED_NAME_PRIVATE_NETWORK_ONLY = "privateNetworkOnly";

	@SerializedName(SERIALIZED_NAME_PRIVATE_NETWORK_ONLY)
	@javax.annotation.Nullable private Boolean privateNetworkOnly;

	public LoadBalancerOptions() {}

	public LoadBalancerOptions accessControl(
			@javax.annotation.Nullable LoadbalancerOptionAccessControl accessControl) {
		this.accessControl = accessControl;
		return this;
	}

	/**
	 * Get accessControl
	 *
	 * @return accessControl
	 */
	@javax.annotation.Nullable public LoadbalancerOptionAccessControl getAccessControl() {
		return accessControl;
	}

	public void setAccessControl(
			@javax.annotation.Nullable LoadbalancerOptionAccessControl accessControl) {
		this.accessControl = accessControl;
	}

	public LoadBalancerOptions ephemeralAddress(
			@javax.annotation.Nullable Boolean ephemeralAddress) {
		this.ephemeralAddress = ephemeralAddress;
		return this;
	}

	/**
	 * This option automates the handling of the external IP address for an Application Load
	 * Balancer. If set to true a new IP address will be automatically created. It will also be
	 * automatically deleted when the Load Balancer is deleted.
	 *
	 * @return ephemeralAddress
	 */
	@javax.annotation.Nullable public Boolean getEphemeralAddress() {
		return ephemeralAddress;
	}

	public void setEphemeralAddress(@javax.annotation.Nullable Boolean ephemeralAddress) {
		this.ephemeralAddress = ephemeralAddress;
	}

	public LoadBalancerOptions observability(
			@javax.annotation.Nullable LoadbalancerOptionObservability observability) {
		this.observability = observability;
		return this;
	}

	/**
	 * Get observability
	 *
	 * @return observability
	 */
	@javax.annotation.Nullable public LoadbalancerOptionObservability getObservability() {
		return observability;
	}

	public void setObservability(
			@javax.annotation.Nullable LoadbalancerOptionObservability observability) {
		this.observability = observability;
	}

	public LoadBalancerOptions privateNetworkOnly(
			@javax.annotation.Nullable Boolean privateNetworkOnly) {
		this.privateNetworkOnly = privateNetworkOnly;
		return this;
	}

	/**
	 * Application Load Balancer is accessible only via a private network ip address. Not changeable
	 * after creation.
	 *
	 * @return privateNetworkOnly
	 */
	@javax.annotation.Nullable public Boolean getPrivateNetworkOnly() {
		return privateNetworkOnly;
	}

	public void setPrivateNetworkOnly(@javax.annotation.Nullable Boolean privateNetworkOnly) {
		this.privateNetworkOnly = privateNetworkOnly;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		LoadBalancerOptions loadBalancerOptions = (LoadBalancerOptions) o;
		return Objects.equals(this.accessControl, loadBalancerOptions.accessControl)
				&& Objects.equals(this.ephemeralAddress, loadBalancerOptions.ephemeralAddress)
				&& Objects.equals(this.observability, loadBalancerOptions.observability)
				&& Objects.equals(this.privateNetworkOnly, loadBalancerOptions.privateNetworkOnly);
	}

	@Override
	public int hashCode() {
		return Objects.hash(accessControl, ephemeralAddress, observability, privateNetworkOnly);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LoadBalancerOptions {\n");
		sb.append("    accessControl: ").append(toIndentedString(accessControl)).append("\n");
		sb.append("    ephemeralAddress: ").append(toIndentedString(ephemeralAddress)).append("\n");
		sb.append("    observability: ").append(toIndentedString(observability)).append("\n");
		sb.append("    privateNetworkOnly: ")
				.append(toIndentedString(privateNetworkOnly))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields =
				new HashSet<String>(
						Arrays.asList(
								"accessControl",
								"ephemeralAddress",
								"observability",
								"privateNetworkOnly"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to LoadBalancerOptions
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!LoadBalancerOptions.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in LoadBalancerOptions is not found in the empty JSON string",
								LoadBalancerOptions.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!LoadBalancerOptions.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `LoadBalancerOptions` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// validate the optional field `accessControl`
		if (jsonObj.get("accessControl") != null && !jsonObj.get("accessControl").isJsonNull()) {
			LoadbalancerOptionAccessControl.validateJsonElement(jsonObj.get("accessControl"));
		}
		// validate the optional field `observability`
		if (jsonObj.get("observability") != null && !jsonObj.get("observability").isJsonNull()) {
			LoadbalancerOptionObservability.validateJsonElement(jsonObj.get("observability"));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!LoadBalancerOptions.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'LoadBalancerOptions' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<LoadBalancerOptions> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(LoadBalancerOptions.class));

			return (TypeAdapter<T>)
					new TypeAdapter<LoadBalancerOptions>() {
						@Override
						public void write(JsonWriter out, LoadBalancerOptions value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public LoadBalancerOptions read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of LoadBalancerOptions given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of LoadBalancerOptions
	 * @throws IOException if the JSON string is invalid with respect to LoadBalancerOptions
	 */
	public static LoadBalancerOptions fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, LoadBalancerOptions.class);
	}

	/**
	 * Convert an instance of LoadBalancerOptions to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
