/*
 * STACKIT Application Load Balancer API
 * This API offers an interface to provision and manage load balancing servers in your STACKIT project. It also has the possibility of pooling target servers for load balancing purposes.  For each application load balancer provided, two VMs are deployed in your OpenStack project subject to a fee.
 *
 * The version of the OpenAPI document: 2beta2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.alb.model;

import cloud.stackit.sdk.alb.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** TargetPoolTlsConfig */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class TargetPoolTlsConfig {
	public static final String SERIALIZED_NAME_CUSTOM_CA = "customCa";

	@SerializedName(SERIALIZED_NAME_CUSTOM_CA)
	@javax.annotation.Nullable private String customCa;

	public static final String SERIALIZED_NAME_ENABLED = "enabled";

	@SerializedName(SERIALIZED_NAME_ENABLED)
	@javax.annotation.Nullable private Boolean enabled;

	public static final String SERIALIZED_NAME_SKIP_CERTIFICATE_VALIDATION =
			"skipCertificateValidation";

	@SerializedName(SERIALIZED_NAME_SKIP_CERTIFICATE_VALIDATION)
	@javax.annotation.Nullable private Boolean skipCertificateValidation;

	public TargetPoolTlsConfig() {}

	public TargetPoolTlsConfig customCa(@javax.annotation.Nullable String customCa) {
		this.customCa = customCa;
		return this;
	}

	/**
	 * Specifies a custom Certificate Authority (CA). When provided, the target pool will trust
	 * certificates signed by this CA, in addition to any system-trusted CAs. This is useful for
	 * scenarios where the target pool needs to communicate with servers using self-signed or
	 * internally-issued certificates.
	 *
	 * @return customCa
	 */
	@javax.annotation.Nullable public String getCustomCa() {
		return customCa;
	}

	public void setCustomCa(@javax.annotation.Nullable String customCa) {
		this.customCa = customCa;
	}

	public TargetPoolTlsConfig enabled(@javax.annotation.Nullable Boolean enabled) {
		this.enabled = enabled;
		return this;
	}

	/**
	 * Enable or disable TLS (Transport Layer Security) for connections to the target pool. When
	 * enabled, the load balancer will establish secure connections using TLS to the target pool.
	 *
	 * @return enabled
	 */
	@javax.annotation.Nullable public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
		this.enabled = enabled;
	}

	public TargetPoolTlsConfig skipCertificateValidation(
			@javax.annotation.Nullable Boolean skipCertificateValidation) {
		this.skipCertificateValidation = skipCertificateValidation;
		return this;
	}

	/**
	 * Bypass certificate validation for TLS connections to the target pool. This option is
	 * insecure.
	 *
	 * @return skipCertificateValidation
	 */
	@javax.annotation.Nullable public Boolean getSkipCertificateValidation() {
		return skipCertificateValidation;
	}

	public void setSkipCertificateValidation(
			@javax.annotation.Nullable Boolean skipCertificateValidation) {
		this.skipCertificateValidation = skipCertificateValidation;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		TargetPoolTlsConfig targetPoolTlsConfig = (TargetPoolTlsConfig) o;
		return Objects.equals(this.customCa, targetPoolTlsConfig.customCa)
				&& Objects.equals(this.enabled, targetPoolTlsConfig.enabled)
				&& Objects.equals(
						this.skipCertificateValidation,
						targetPoolTlsConfig.skipCertificateValidation);
	}

	@Override
	public int hashCode() {
		return Objects.hash(customCa, enabled, skipCertificateValidation);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class TargetPoolTlsConfig {\n");
		sb.append("    customCa: ").append(toIndentedString(customCa)).append("\n");
		sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
		sb.append("    skipCertificateValidation: ")
				.append(toIndentedString(skipCertificateValidation))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields =
				new HashSet<String>(
						Arrays.asList("customCa", "enabled", "skipCertificateValidation"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to TargetPoolTlsConfig
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!TargetPoolTlsConfig.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in TargetPoolTlsConfig is not found in the empty JSON string",
								TargetPoolTlsConfig.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!TargetPoolTlsConfig.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `TargetPoolTlsConfig` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		if ((jsonObj.get("customCa") != null && !jsonObj.get("customCa").isJsonNull())
				&& !jsonObj.get("customCa").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							"Expected the field `customCa` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("customCa").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!TargetPoolTlsConfig.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'TargetPoolTlsConfig' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<TargetPoolTlsConfig> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(TargetPoolTlsConfig.class));

			return (TypeAdapter<T>)
					new TypeAdapter<TargetPoolTlsConfig>() {
						@Override
						public void write(JsonWriter out, TargetPoolTlsConfig value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public TargetPoolTlsConfig read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of TargetPoolTlsConfig given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of TargetPoolTlsConfig
	 * @throws IOException if the JSON string is invalid with respect to TargetPoolTlsConfig
	 */
	public static TargetPoolTlsConfig fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, TargetPoolTlsConfig.class);
	}

	/**
	 * Convert an instance of TargetPoolTlsConfig to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
