/*
 * STACKIT IaaS API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2alpha1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.v2alpha1api.model;

import cloud.stackit.sdk.iaas.v2alpha1api.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Object that represents the request body for a routing table update. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class UpdateRoutingTableOfAreaPayload {
	public static final String SERIALIZED_NAME_DESCRIPTION = "description";

	@SerializedName(SERIALIZED_NAME_DESCRIPTION)
	@javax.annotation.Nullable private String description;

	public static final String SERIALIZED_NAME_DYNAMIC_ROUTES = "dynamicRoutes";

	@SerializedName(SERIALIZED_NAME_DYNAMIC_ROUTES)
	@javax.annotation.Nullable private Boolean dynamicRoutes;

	public static final String SERIALIZED_NAME_LABELS = "labels";

	@SerializedName(SERIALIZED_NAME_LABELS)
	@javax.annotation.Nullable private Object labels;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	@javax.annotation.Nullable private String name;

	public static final String SERIALIZED_NAME_SYSTEM_ROUTES = "systemRoutes";

	@SerializedName(SERIALIZED_NAME_SYSTEM_ROUTES)
	@javax.annotation.Nullable private Boolean systemRoutes;

	public UpdateRoutingTableOfAreaPayload() {}

	public UpdateRoutingTableOfAreaPayload description(
			@javax.annotation.Nullable String description) {
		this.description = description;
		return this;
	}

	/**
	 * Description Object. Allows string up to 255 Characters.
	 *
	 * @return description
	 */
	@javax.annotation.Nullable public String getDescription() {
		return description;
	}

	public void setDescription(@javax.annotation.Nullable String description) {
		this.description = description;
	}

	public UpdateRoutingTableOfAreaPayload dynamicRoutes(
			@javax.annotation.Nullable Boolean dynamicRoutes) {
		this.dynamicRoutes = dynamicRoutes;
		return this;
	}

	/**
	 * The update config setting for a routing table which allows propagation of dynamic routes to
	 * this routing table.
	 *
	 * @return dynamicRoutes
	 */
	@javax.annotation.Nullable public Boolean getDynamicRoutes() {
		return dynamicRoutes;
	}

	public void setDynamicRoutes(@javax.annotation.Nullable Boolean dynamicRoutes) {
		this.dynamicRoutes = dynamicRoutes;
	}

	public UpdateRoutingTableOfAreaPayload labels(@javax.annotation.Nullable Object labels) {
		this.labels = labels;
		return this;
	}

	/**
	 * Object that represents the labels of an object. Regex for keys:
	 * &#x60;^(?&#x3D;.{1,63}$)([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$&#x60;. Regex for values:
	 * &#x60;^(?&#x3D;.{0,63}$)(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])*$&#x60;. Providing a
	 * &#x60;null&#x60; value for a key will remove that key. The &#x60;stackit-&#x60; prefix is
	 * reserved and cannot be used for Keys.
	 *
	 * @return labels
	 */
	@javax.annotation.Nullable public Object getLabels() {
		return labels;
	}

	public void setLabels(@javax.annotation.Nullable Object labels) {
		this.labels = labels;
	}

	public UpdateRoutingTableOfAreaPayload name(@javax.annotation.Nullable String name) {
		this.name = name;
		return this;
	}

	/**
	 * The name for a General Object. Matches Names and also UUIDs.
	 *
	 * @return name
	 */
	@javax.annotation.Nullable public String getName() {
		return name;
	}

	public void setName(@javax.annotation.Nullable String name) {
		this.name = name;
	}

	public UpdateRoutingTableOfAreaPayload systemRoutes(
			@javax.annotation.Nullable Boolean systemRoutes) {
		this.systemRoutes = systemRoutes;
		return this;
	}

	/**
	 * The update config setting for a routing table which allows installation of automatic system
	 * routes for connectivity between projects in the same SNA.
	 *
	 * @return systemRoutes
	 */
	@javax.annotation.Nullable public Boolean getSystemRoutes() {
		return systemRoutes;
	}

	public void setSystemRoutes(@javax.annotation.Nullable Boolean systemRoutes) {
		this.systemRoutes = systemRoutes;
	}

	/**
	 * A container for additional, undeclared properties. This is a holder for any undeclared
	 * properties as specified with the 'additionalProperties' keyword in the OAS document.
	 */
	private Map<String, Object> additionalProperties;

	/**
	 * Set the additional (undeclared) property with the specified name and value. If the property
	 * does not already exist, create it otherwise replace it.
	 *
	 * @param key name of the property
	 * @param value value of the property
	 * @return the UpdateRoutingTableOfAreaPayload instance itself
	 */
	public UpdateRoutingTableOfAreaPayload putAdditionalProperty(String key, Object value) {
		if (this.additionalProperties == null) {
			this.additionalProperties = new HashMap<String, Object>();
		}
		this.additionalProperties.put(key, value);
		return this;
	}

	/**
	 * Return the additional (undeclared) property.
	 *
	 * @return a map of objects
	 */
	public Map<String, Object> getAdditionalProperties() {
		return additionalProperties;
	}

	/**
	 * Return the additional (undeclared) property with the specified name.
	 *
	 * @param key name of the property
	 * @return an object
	 */
	public Object getAdditionalProperty(String key) {
		if (this.additionalProperties == null) {
			return null;
		}
		return this.additionalProperties.get(key);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		UpdateRoutingTableOfAreaPayload updateRoutingTableOfAreaPayload =
				(UpdateRoutingTableOfAreaPayload) o;
		return Objects.equals(this.description, updateRoutingTableOfAreaPayload.description)
				&& Objects.equals(this.dynamicRoutes, updateRoutingTableOfAreaPayload.dynamicRoutes)
				&& Objects.equals(this.labels, updateRoutingTableOfAreaPayload.labels)
				&& Objects.equals(this.name, updateRoutingTableOfAreaPayload.name)
				&& Objects.equals(this.systemRoutes, updateRoutingTableOfAreaPayload.systemRoutes)
				&& Objects.equals(
						this.additionalProperties,
						updateRoutingTableOfAreaPayload.additionalProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(
				description, dynamicRoutes, labels, name, systemRoutes, additionalProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class UpdateRoutingTableOfAreaPayload {\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    dynamicRoutes: ").append(toIndentedString(dynamicRoutes)).append("\n");
		sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    systemRoutes: ").append(toIndentedString(systemRoutes)).append("\n");
		sb.append("    additionalProperties: ")
				.append(toIndentedString(additionalProperties))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields =
				new HashSet<String>(
						Arrays.asList(
								"description", "dynamicRoutes", "labels", "name", "systemRoutes"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to
	 *     UpdateRoutingTableOfAreaPayload
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!UpdateRoutingTableOfAreaPayload.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in UpdateRoutingTableOfAreaPayload is not found in the empty JSON string",
								UpdateRoutingTableOfAreaPayload.openapiRequiredFields.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull())
				&& !jsonObj.get("description").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `description` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("description").toString()));
		}
		if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull())
				&& !jsonObj.get("name").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `name` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("name").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!UpdateRoutingTableOfAreaPayload.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'UpdateRoutingTableOfAreaPayload' and its
				// subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<UpdateRoutingTableOfAreaPayload> thisAdapter =
					gson.getDelegateAdapter(
							this, TypeToken.get(UpdateRoutingTableOfAreaPayload.class));

			return (TypeAdapter<T>)
					new TypeAdapter<UpdateRoutingTableOfAreaPayload>() {
						@Override
						public void write(JsonWriter out, UpdateRoutingTableOfAreaPayload value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							obj.remove("additionalProperties");
							// serialize additional properties
							if (value.getAdditionalProperties() != null) {
								for (Map.Entry<String, Object> entry :
										value.getAdditionalProperties().entrySet()) {
									if (entry.getValue() instanceof String)
										obj.addProperty(entry.getKey(), (String) entry.getValue());
									else if (entry.getValue() instanceof Number)
										obj.addProperty(entry.getKey(), (Number) entry.getValue());
									else if (entry.getValue() instanceof Boolean)
										obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
									else if (entry.getValue() instanceof Character)
										obj.addProperty(
												entry.getKey(), (Character) entry.getValue());
									else {
										JsonElement jsonElement = gson.toJsonTree(entry.getValue());
										if (jsonElement.isJsonArray()) {
											obj.add(entry.getKey(), jsonElement.getAsJsonArray());
										} else {
											obj.add(entry.getKey(), jsonElement.getAsJsonObject());
										}
									}
								}
							}
							elementAdapter.write(out, obj);
						}

						@Override
						public UpdateRoutingTableOfAreaPayload read(JsonReader in)
								throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							JsonObject jsonObj = jsonElement.getAsJsonObject();
							// store additional fields in the deserialized instance
							UpdateRoutingTableOfAreaPayload instance =
									thisAdapter.fromJsonTree(jsonObj);
							for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
								if (!openapiFields.contains(entry.getKey())) {
									if (entry.getValue().isJsonPrimitive()) { // primitive type
										if (entry.getValue().getAsJsonPrimitive().isString())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsString());
										else if (entry.getValue().getAsJsonPrimitive().isNumber())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsNumber());
										else if (entry.getValue().getAsJsonPrimitive().isBoolean())
											instance.putAdditionalProperty(
													entry.getKey(),
													entry.getValue().getAsBoolean());
										else
											throw new IllegalArgumentException(
													String.format(
															java.util.Locale.ROOT,
															"The field `%s` has unknown primitive type. Value: %s",
															entry.getKey(),
															entry.getValue().toString()));
									} else if (entry.getValue().isJsonArray()) {
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), List.class));
									} else { // JSON object
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), HashMap.class));
									}
								}
							}
							return instance;
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of UpdateRoutingTableOfAreaPayload given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of UpdateRoutingTableOfAreaPayload
	 * @throws IOException if the JSON string is invalid with respect to
	 *     UpdateRoutingTableOfAreaPayload
	 */
	public static UpdateRoutingTableOfAreaPayload fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, UpdateRoutingTableOfAreaPayload.class);
	}

	/**
	 * Convert an instance of UpdateRoutingTableOfAreaPayload to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
