/*
 * STACKIT IaaS API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2alpha1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.v2alpha1api.model;

import cloud.stackit.sdk.iaas.v2alpha1api.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class VPCNetworkRange extends AbstractOpenApiSchema {
	private static final Logger log = Logger.getLogger(VPCNetworkRange.class.getName());

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!VPCNetworkRange.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'VPCNetworkRange' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<VPCNetworkRangeIPv4> adapterVPCNetworkRangeIPv4 =
					gson.getDelegateAdapter(this, TypeToken.get(VPCNetworkRangeIPv4.class));
			final TypeAdapter<VPCNetworkRangeIPv6> adapterVPCNetworkRangeIPv6 =
					gson.getDelegateAdapter(this, TypeToken.get(VPCNetworkRangeIPv6.class));

			return (TypeAdapter<T>)
					new TypeAdapter<VPCNetworkRange>() {
						@Override
						public void write(JsonWriter out, VPCNetworkRange value)
								throws IOException {
							if (value == null || value.getActualInstance() == null) {
								elementAdapter.write(out, null);
								return;
							}

							// check if the actual instance is of the type `VPCNetworkRangeIPv4`
							if (value.getActualInstance() instanceof VPCNetworkRangeIPv4) {
								JsonElement element =
										adapterVPCNetworkRangeIPv4.toJsonTree(
												(VPCNetworkRangeIPv4) value.getActualInstance());
								elementAdapter.write(out, element);
								return;
							}
							// check if the actual instance is of the type `VPCNetworkRangeIPv6`
							if (value.getActualInstance() instanceof VPCNetworkRangeIPv6) {
								JsonElement element =
										adapterVPCNetworkRangeIPv6.toJsonTree(
												(VPCNetworkRangeIPv6) value.getActualInstance());
								elementAdapter.write(out, element);
								return;
							}
							throw new IOException(
									"Failed to serialize as the type doesn't match oneOf schemas: VPCNetworkRangeIPv4, VPCNetworkRangeIPv6");
						}

						@Override
						public VPCNetworkRange read(JsonReader in) throws IOException {
							Object deserialized = null;
							JsonElement jsonElement = elementAdapter.read(in);

							int match = 0;
							ArrayList<String> errorMessages = new ArrayList<>();
							TypeAdapter actualAdapter = elementAdapter;

							// deserialize VPCNetworkRangeIPv4
							try {
								// validate the JSON object to see if any exception is thrown
								VPCNetworkRangeIPv4.validateJsonElement(jsonElement);
								actualAdapter = adapterVPCNetworkRangeIPv4;
								match++;
								log.log(
										Level.FINER,
										"Input data matches schema 'VPCNetworkRangeIPv4'");
							} catch (Exception e) {
								// deserialization failed, continue
								errorMessages.add(
										String.format(
												java.util.Locale.ROOT,
												"Deserialization for VPCNetworkRangeIPv4 failed with `%s`.",
												e.getMessage()));
								log.log(
										Level.FINER,
										"Input data does not match schema 'VPCNetworkRangeIPv4'",
										e);
							}
							// deserialize VPCNetworkRangeIPv6
							try {
								// validate the JSON object to see if any exception is thrown
								VPCNetworkRangeIPv6.validateJsonElement(jsonElement);
								actualAdapter = adapterVPCNetworkRangeIPv6;
								match++;
								log.log(
										Level.FINER,
										"Input data matches schema 'VPCNetworkRangeIPv6'");
							} catch (Exception e) {
								// deserialization failed, continue
								errorMessages.add(
										String.format(
												java.util.Locale.ROOT,
												"Deserialization for VPCNetworkRangeIPv6 failed with `%s`.",
												e.getMessage()));
								log.log(
										Level.FINER,
										"Input data does not match schema 'VPCNetworkRangeIPv6'",
										e);
							}

							if (match == 1) {
								VPCNetworkRange ret = new VPCNetworkRange();
								ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
								return ret;
							}

							throw new IOException(
									String.format(
											java.util.Locale.ROOT,
											"Failed deserialization for VPCNetworkRange: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s",
											match,
											errorMessages,
											jsonElement.toString()));
						}
					}.nullSafe();
		}
	}

	// store a list of schema names defined in oneOf
	public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

	public VPCNetworkRange() {
		super("oneOf", Boolean.FALSE);
	}

	public VPCNetworkRange(Object o) {
		super("oneOf", Boolean.FALSE);
		setActualInstance(o);
	}

	static {
		schemas.put("VPCNetworkRangeIPv4", VPCNetworkRangeIPv4.class);
		schemas.put("VPCNetworkRangeIPv6", VPCNetworkRangeIPv6.class);
	}

	@Override
	public Map<String, Class<?>> getSchemas() {
		return VPCNetworkRange.schemas;
	}

	/**
	 * Set the instance that matches the oneOf child schema, check the instance parameter is valid
	 * against the oneOf child schemas: VPCNetworkRangeIPv4, VPCNetworkRangeIPv6
	 *
	 * <p>It could be an instance of the 'oneOf' schemas.
	 */
	@Override
	public void setActualInstance(Object instance) {
		if (instance instanceof VPCNetworkRangeIPv4) {
			super.setActualInstance(instance);
			return;
		}

		if (instance instanceof VPCNetworkRangeIPv6) {
			super.setActualInstance(instance);
			return;
		}

		throw new RuntimeException(
				"Invalid instance type. Must be VPCNetworkRangeIPv4, VPCNetworkRangeIPv6");
	}

	/**
	 * Get the actual instance, which can be the following: VPCNetworkRangeIPv4, VPCNetworkRangeIPv6
	 *
	 * @return The actual instance (VPCNetworkRangeIPv4, VPCNetworkRangeIPv6)
	 */
	@SuppressWarnings("unchecked")
	@Override
	public Object getActualInstance() {
		return super.getActualInstance();
	}

	/**
	 * Get the actual instance of `VPCNetworkRangeIPv4`. If the actual instance is not
	 * `VPCNetworkRangeIPv4`, the ClassCastException will be thrown.
	 *
	 * @return The actual instance of `VPCNetworkRangeIPv4`
	 * @throws ClassCastException if the instance is not `VPCNetworkRangeIPv4`
	 */
	public VPCNetworkRangeIPv4 getVPCNetworkRangeIPv4() throws ClassCastException {
		return (VPCNetworkRangeIPv4) super.getActualInstance();
	}

	/**
	 * Get the actual instance of `VPCNetworkRangeIPv6`. If the actual instance is not
	 * `VPCNetworkRangeIPv6`, the ClassCastException will be thrown.
	 *
	 * @return The actual instance of `VPCNetworkRangeIPv6`
	 * @throws ClassCastException if the instance is not `VPCNetworkRangeIPv6`
	 */
	public VPCNetworkRangeIPv6 getVPCNetworkRangeIPv6() throws ClassCastException {
		return (VPCNetworkRangeIPv6) super.getActualInstance();
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to VPCNetworkRange
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		// validate oneOf schemas one by one
		int validCount = 0;
		ArrayList<String> errorMessages = new ArrayList<>();
		// validate the json string with VPCNetworkRangeIPv4
		try {
			VPCNetworkRangeIPv4.validateJsonElement(jsonElement);
			validCount++;
		} catch (Exception e) {
			errorMessages.add(
					String.format(
							java.util.Locale.ROOT,
							"Deserialization for VPCNetworkRangeIPv4 failed with `%s`.",
							e.getMessage()));
			// continue to the next one
		}
		// validate the json string with VPCNetworkRangeIPv6
		try {
			VPCNetworkRangeIPv6.validateJsonElement(jsonElement);
			validCount++;
		} catch (Exception e) {
			errorMessages.add(
					String.format(
							java.util.Locale.ROOT,
							"Deserialization for VPCNetworkRangeIPv6 failed with `%s`.",
							e.getMessage()));
			// continue to the next one
		}
		if (validCount != 1) {
			throw new IOException(
					String.format(
							java.util.Locale.ROOT,
							"The JSON string is invalid for VPCNetworkRange with oneOf schemas: VPCNetworkRangeIPv4, VPCNetworkRangeIPv6. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s",
							validCount,
							errorMessages,
							jsonElement.toString()));
		}
	}

	/**
	 * Create an instance of VPCNetworkRange given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of VPCNetworkRange
	 * @throws IOException if the JSON string is invalid with respect to VPCNetworkRange
	 */
	public static VPCNetworkRange fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, VPCNetworkRange.class);
	}

	/**
	 * Convert an instance of VPCNetworkRange to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
