/*
 * STACKIT Automation Service API
 * API endpoints for automation management .
 *
 * The version of the OpenAPI document: 1beta.0
 * Contact: support@stackit.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.automation.v1betaapi.model;

import cloud.stackit.sdk.automation.v1betaapi.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** SchedulePatchRequest */
@javax.annotation.Generated(value = "JavaGenerator", comments = "Generator version: 7.19.0")
public class SchedulePatchRequest {
	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	@javax.annotation.Nullable private String name;

	public static final String SERIALIZED_NAME_RRULE = "rrule";

	@SerializedName(SERIALIZED_NAME_RRULE)
	@javax.annotation.Nullable private String rrule;

	public static final String SERIALIZED_NAME_WORKFLOW_CONFIG = "workflowConfig";

	@SerializedName(SERIALIZED_NAME_WORKFLOW_CONFIG)
	@javax.annotation.Nullable private Map<String, Object> workflowConfig = new HashMap<>();

	public SchedulePatchRequest() {}

	public SchedulePatchRequest name(@javax.annotation.Nullable String name) {
		this.name = name;
		return this;
	}

	/**
	 * Get name
	 *
	 * @return name
	 */
	@javax.annotation.Nullable public String getName() {
		return name;
	}

	public void setName(@javax.annotation.Nullable String name) {
		this.name = name;
	}

	public SchedulePatchRequest rrule(@javax.annotation.Nullable String rrule) {
		this.rrule = rrule;
		return this;
	}

	/**
	 * Get rrule
	 *
	 * @return rrule
	 */
	@javax.annotation.Nullable public String getRrule() {
		return rrule;
	}

	public void setRrule(@javax.annotation.Nullable String rrule) {
		this.rrule = rrule;
	}

	public SchedulePatchRequest workflowConfig(
			@javax.annotation.Nullable Map<String, Object> workflowConfig) {
		this.workflowConfig = workflowConfig;
		return this;
	}

	public SchedulePatchRequest putWorkflowConfigItem(String key, Object workflowConfigItem) {
		if (this.workflowConfig == null) {
			this.workflowConfig = new HashMap<>();
		}
		this.workflowConfig.put(key, workflowConfigItem);
		return this;
	}

	/**
	 * Get workflowConfig
	 *
	 * @return workflowConfig
	 */
	@javax.annotation.Nullable public Map<String, Object> getWorkflowConfig() {
		return workflowConfig;
	}

	public void setWorkflowConfig(@javax.annotation.Nullable Map<String, Object> workflowConfig) {
		this.workflowConfig = workflowConfig;
	}

	/**
	 * A container for additional, undeclared properties. This is a holder for any undeclared
	 * properties as specified with the 'additionalProperties' keyword in the OAS document.
	 */
	private Map<String, Object> additionalProperties;

	/**
	 * Set the additional (undeclared) property with the specified name and value. If the property
	 * does not already exist, create it otherwise replace it.
	 *
	 * @param key name of the property
	 * @param value value of the property
	 * @return the SchedulePatchRequest instance itself
	 */
	public SchedulePatchRequest putAdditionalProperty(String key, Object value) {
		if (this.additionalProperties == null) {
			this.additionalProperties = new HashMap<String, Object>();
		}
		this.additionalProperties.put(key, value);
		return this;
	}

	/**
	 * Return the additional (undeclared) property.
	 *
	 * @return a map of objects
	 */
	public Map<String, Object> getAdditionalProperties() {
		return additionalProperties;
	}

	/**
	 * Return the additional (undeclared) property with the specified name.
	 *
	 * @param key name of the property
	 * @return an object
	 */
	public Object getAdditionalProperty(String key) {
		if (this.additionalProperties == null) {
			return null;
		}
		return this.additionalProperties.get(key);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SchedulePatchRequest schedulePatchRequest = (SchedulePatchRequest) o;
		return Objects.equals(this.name, schedulePatchRequest.name)
				&& Objects.equals(this.rrule, schedulePatchRequest.rrule)
				&& Objects.equals(this.workflowConfig, schedulePatchRequest.workflowConfig)
				&& Objects.equals(
						this.additionalProperties, schedulePatchRequest.additionalProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, rrule, workflowConfig, additionalProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SchedulePatchRequest {\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    rrule: ").append(toIndentedString(rrule)).append("\n");
		sb.append("    workflowConfig: ").append(toIndentedString(workflowConfig)).append("\n");
		sb.append("    additionalProperties: ")
				.append(toIndentedString(additionalProperties))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("name", "rrule", "workflowConfig"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to SchedulePatchRequest
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!SchedulePatchRequest.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in SchedulePatchRequest is not found in the empty JSON string",
								SchedulePatchRequest.openapiRequiredFields.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull())
				&& !jsonObj.get("name").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `name` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("name").toString()));
		}
		if ((jsonObj.get("rrule") != null && !jsonObj.get("rrule").isJsonNull())
				&& !jsonObj.get("rrule").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `rrule` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("rrule").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!SchedulePatchRequest.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'SchedulePatchRequest' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<SchedulePatchRequest> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(SchedulePatchRequest.class));

			return (TypeAdapter<T>)
					new TypeAdapter<SchedulePatchRequest>() {
						@Override
						public void write(JsonWriter out, SchedulePatchRequest value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							obj.remove("additionalProperties");
							// serialize additional properties
							if (value.getAdditionalProperties() != null) {
								for (Map.Entry<String, Object> entry :
										value.getAdditionalProperties().entrySet()) {
									if (entry.getValue() instanceof String)
										obj.addProperty(entry.getKey(), (String) entry.getValue());
									else if (entry.getValue() instanceof Number)
										obj.addProperty(entry.getKey(), (Number) entry.getValue());
									else if (entry.getValue() instanceof Boolean)
										obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
									else if (entry.getValue() instanceof Character)
										obj.addProperty(
												entry.getKey(), (Character) entry.getValue());
									else {
										JsonElement jsonElement = gson.toJsonTree(entry.getValue());
										if (jsonElement.isJsonArray()) {
											obj.add(entry.getKey(), jsonElement.getAsJsonArray());
										} else {
											obj.add(entry.getKey(), jsonElement.getAsJsonObject());
										}
									}
								}
							}
							elementAdapter.write(out, obj);
						}

						@Override
						public SchedulePatchRequest read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							JsonObject jsonObj = jsonElement.getAsJsonObject();
							// store additional fields in the deserialized instance
							SchedulePatchRequest instance = thisAdapter.fromJsonTree(jsonObj);
							for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
								if (!openapiFields.contains(entry.getKey())) {
									if (entry.getValue().isJsonPrimitive()) { // primitive type
										if (entry.getValue().getAsJsonPrimitive().isString())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsString());
										else if (entry.getValue().getAsJsonPrimitive().isNumber())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsNumber());
										else if (entry.getValue().getAsJsonPrimitive().isBoolean())
											instance.putAdditionalProperty(
													entry.getKey(),
													entry.getValue().getAsBoolean());
										else
											throw new IllegalArgumentException(
													String.format(
															java.util.Locale.ROOT,
															"The field `%s` has unknown primitive type. Value: %s",
															entry.getKey(),
															entry.getValue().toString()));
									} else if (entry.getValue().isJsonArray()) {
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), List.class));
									} else { // JSON object
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), HashMap.class));
									}
								}
							}
							return instance;
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of SchedulePatchRequest given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of SchedulePatchRequest
	 * @throws IOException if the JSON string is invalid with respect to SchedulePatchRequest
	 */
	public static SchedulePatchRequest fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, SchedulePatchRequest.class);
	}

	/**
	 * Convert an instance of SchedulePatchRequest to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
