/*
 * IaaS-API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2beta1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.model;

import cloud.stackit.sdk.iaas.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** ManagementRouteDestination */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class ManagementRouteDestination {
	public static final String SERIALIZED_NAME_TYPE = "type";

	@SerializedName(SERIALIZED_NAME_TYPE)
	@javax.annotation.Nonnull
	protected String type;

	public static final String SERIALIZED_NAME_VALUE = "value";

	@SerializedName(SERIALIZED_NAME_VALUE)
	@javax.annotation.Nonnull
	private String value;

	public ManagementRouteDestination() {
		this.type = this.getClass().getSimpleName();
	}

	public ManagementRouteDestination type(@javax.annotation.Nonnull String type) {
		this.type = type;
		return this;
	}

	/**
	 * Get type
	 *
	 * @return type
	 */
	@javax.annotation.Nonnull
	public String getType() {
		return type;
	}

	public void setType(@javax.annotation.Nonnull String type) {
		this.type = type;
	}

	public ManagementRouteDestination value(@javax.annotation.Nonnull String value) {
		this.value = value;
		return this;
	}

	/**
	 * An CIDRv6 string.
	 *
	 * @return value
	 */
	@javax.annotation.Nonnull
	public String getValue() {
		return value;
	}

	public void setValue(@javax.annotation.Nonnull String value) {
		this.value = value;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ManagementRouteDestination managementRouteDestination = (ManagementRouteDestination) o;
		return Objects.equals(this.type, managementRouteDestination.type)
				&& Objects.equals(this.value, managementRouteDestination.value);
	}

	@Override
	public int hashCode() {
		return Objects.hash(type, value);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ManagementRouteDestination {\n");
		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    value: ").append(toIndentedString(value)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("type", "value"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "value"));
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to ManagementRouteDestination
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!ManagementRouteDestination.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in ManagementRouteDestination is not found in the empty JSON string",
								ManagementRouteDestination.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!ManagementRouteDestination.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `ManagementRouteDestination` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}

		// check to make sure all required properties/fields are present in the JSON string
		for (String requiredField : ManagementRouteDestination.openapiRequiredFields) {
			if (jsonElement.getAsJsonObject().get(requiredField) == null) {
				throw new IllegalArgumentException(
						String.format(
								"The required field `%s` is not found in the JSON string: %s",
								requiredField, jsonElement.toString()));
			}
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!ManagementRouteDestination.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'ManagementRouteDestination' and its
				// subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<ManagementRouteDestination> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(ManagementRouteDestination.class));

			return (TypeAdapter<T>)
					new TypeAdapter<ManagementRouteDestination>() {
						@Override
						public void write(JsonWriter out, ManagementRouteDestination value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public ManagementRouteDestination read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of ManagementRouteDestination given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of ManagementRouteDestination
	 * @throws IOException if the JSON string is invalid with respect to ManagementRouteDestination
	 */
	public static ManagementRouteDestination fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, ManagementRouteDestination.class);
	}

	/**
	 * Convert an instance of ManagementRouteDestination to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
