/*
 * IaaS-API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2beta1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.model;

import cloud.stackit.sdk.iaas.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Object that represents a range of ports. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class PortRange {
	public static final String SERIALIZED_NAME_MAX = "max";

	@SerializedName(SERIALIZED_NAME_MAX)
	@javax.annotation.Nonnull
	private Long max;

	public static final String SERIALIZED_NAME_MIN = "min";

	@SerializedName(SERIALIZED_NAME_MIN)
	@javax.annotation.Nonnull
	private Long min;

	public PortRange() {}

	public PortRange max(@javax.annotation.Nonnull Long max) {
		this.max = max;
		return this;
	}

	/**
	 * The maximum port number. Should be greater or equal to the minimum. minimum: 0 maximum: 65535
	 *
	 * @return max
	 */
	@javax.annotation.Nonnull
	public Long getMax() {
		return max;
	}

	public void setMax(@javax.annotation.Nonnull Long max) {
		this.max = max;
	}

	public PortRange min(@javax.annotation.Nonnull Long min) {
		this.min = min;
		return this;
	}

	/**
	 * The minimum port number. Should be less or equal to the maximum. minimum: 0 maximum: 65535
	 *
	 * @return min
	 */
	@javax.annotation.Nonnull
	public Long getMin() {
		return min;
	}

	public void setMin(@javax.annotation.Nonnull Long min) {
		this.min = min;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PortRange portRange = (PortRange) o;
		return Objects.equals(this.max, portRange.max) && Objects.equals(this.min, portRange.min);
	}

	@Override
	public int hashCode() {
		return Objects.hash(max, min);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PortRange {\n");
		sb.append("    max: ").append(toIndentedString(max)).append("\n");
		sb.append("    min: ").append(toIndentedString(min)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("max", "min"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(Arrays.asList("max", "min"));
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to PortRange
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!PortRange.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in PortRange is not found in the empty JSON string",
								PortRange.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!PortRange.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `PortRange` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}

		// check to make sure all required properties/fields are present in the JSON string
		for (String requiredField : PortRange.openapiRequiredFields) {
			if (jsonElement.getAsJsonObject().get(requiredField) == null) {
				throw new IllegalArgumentException(
						String.format(
								"The required field `%s` is not found in the JSON string: %s",
								requiredField, jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!PortRange.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'PortRange' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<PortRange> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(PortRange.class));

			return (TypeAdapter<T>)
					new TypeAdapter<PortRange>() {
						@Override
						public void write(JsonWriter out, PortRange value) throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public PortRange read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of PortRange given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of PortRange
	 * @throws IOException if the JSON string is invalid with respect to PortRange
	 */
	public static PortRange fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, PortRange.class);
	}

	/**
	 * Convert an instance of PortRange to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
