/*
 * IaaS-API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.model;

import cloud.stackit.sdk.iaas.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Object that represents a single resource quota. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.14.0")
public class Quota {
	public static final String SERIALIZED_NAME_LIMIT = "limit";

	@SerializedName(SERIALIZED_NAME_LIMIT)
	@javax.annotation.Nonnull
	private Long limit;

	public static final String SERIALIZED_NAME_USAGE = "usage";

	@SerializedName(SERIALIZED_NAME_USAGE)
	@javax.annotation.Nonnull
	private Long usage;

	public Quota() {}

	public Quota limit(@javax.annotation.Nonnull Long limit) {
		this.limit = limit;
		return this;
	}

	/**
	 * Get limit
	 *
	 * @return limit
	 */
	@javax.annotation.Nonnull
	public Long getLimit() {
		return limit;
	}

	public void setLimit(@javax.annotation.Nonnull Long limit) {
		this.limit = limit;
	}

	public Quota usage(@javax.annotation.Nonnull Long usage) {
		this.usage = usage;
		return this;
	}

	/**
	 * Get usage
	 *
	 * @return usage
	 */
	@javax.annotation.Nonnull
	public Long getUsage() {
		return usage;
	}

	public void setUsage(@javax.annotation.Nonnull Long usage) {
		this.usage = usage;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Quota quota = (Quota) o;
		return Objects.equals(this.limit, quota.limit) && Objects.equals(this.usage, quota.usage);
	}

	@Override
	public int hashCode() {
		return Objects.hash(limit, usage);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Quota {\n");
		sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
		sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("limit", "usage"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(Arrays.asList("limit", "usage"));
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to Quota
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!Quota.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in Quota is not found in the empty JSON string",
								Quota.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!Quota.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `Quota` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}

		// check to make sure all required properties/fields are present in the JSON string
		for (String requiredField : Quota.openapiRequiredFields) {
			if (jsonElement.getAsJsonObject().get(requiredField) == null) {
				throw new IllegalArgumentException(
						String.format(
								"The required field `%s` is not found in the JSON string: %s",
								requiredField, jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!Quota.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'Quota' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<Quota> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(Quota.class));

			return (TypeAdapter<T>)
					new TypeAdapter<Quota>() {
						@Override
						public void write(JsonWriter out, Quota value) throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public Quota read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of Quota given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of Quota
	 * @throws IOException if the JSON string is invalid with respect to Quota
	 */
	public static Quota fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, Quota.class);
	}

	/**
	 * Convert an instance of Quota to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
