/*
 * IaaS-API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.model;

import cloud.stackit.sdk.iaas.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** The basic properties of a regional network area. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class RegionalArea {
	public static final String SERIALIZED_NAME_IPV4 = "ipv4";

	@SerializedName(SERIALIZED_NAME_IPV4)
	@javax.annotation.Nullable private RegionalAreaIPv4 ipv4;

	public static final String SERIALIZED_NAME_STATUS = "status";

	@SerializedName(SERIALIZED_NAME_STATUS)
	@javax.annotation.Nullable private String status;

	public RegionalArea() {}

	public RegionalArea(String status) {
		this();
		this.status = status;
	}

	public RegionalArea ipv4(@javax.annotation.Nullable RegionalAreaIPv4 ipv4) {
		this.ipv4 = ipv4;
		return this;
	}

	/**
	 * Get ipv4
	 *
	 * @return ipv4
	 */
	@javax.annotation.Nullable public RegionalAreaIPv4 getIpv4() {
		return ipv4;
	}

	public void setIpv4(@javax.annotation.Nullable RegionalAreaIPv4 ipv4) {
		this.ipv4 = ipv4;
	}

	/**
	 * The state of a resource object. Possible values: &#x60;CREATING&#x60;, &#x60;CREATED&#x60;,
	 * &#x60;DELETING&#x60;, &#x60;DELETED&#x60;, &#x60;FAILED&#x60;, &#x60;UPDATED&#x60;,
	 * &#x60;UPDATING&#x60;.
	 *
	 * @return status
	 */
	@javax.annotation.Nullable public String getStatus() {
		return status;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RegionalArea regionalArea = (RegionalArea) o;
		return Objects.equals(this.ipv4, regionalArea.ipv4)
				&& Objects.equals(this.status, regionalArea.status);
	}

	@Override
	public int hashCode() {
		return Objects.hash(ipv4, status);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RegionalArea {\n");
		sb.append("    ipv4: ").append(toIndentedString(ipv4)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("ipv4", "status"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to RegionalArea
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!RegionalArea.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in RegionalArea is not found in the empty JSON string",
								RegionalArea.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!RegionalArea.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `RegionalArea` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// validate the optional field `ipv4`
		if (jsonObj.get("ipv4") != null && !jsonObj.get("ipv4").isJsonNull()) {
			RegionalAreaIPv4.validateJsonElement(jsonObj.get("ipv4"));
		}
		if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull())
				&& !jsonObj.get("status").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							"Expected the field `status` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("status").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!RegionalArea.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'RegionalArea' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<RegionalArea> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(RegionalArea.class));

			return (TypeAdapter<T>)
					new TypeAdapter<RegionalArea>() {
						@Override
						public void write(JsonWriter out, RegionalArea value) throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public RegionalArea read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of RegionalArea given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of RegionalArea
	 * @throws IOException if the JSON string is invalid with respect to RegionalArea
	 */
	public static RegionalArea fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, RegionalArea.class);
	}

	/**
	 * Convert an instance of RegionalArea to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
