/*
 * IaaS-API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.model;

import cloud.stackit.sdk.iaas.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class RouteDestination extends AbstractOpenApiSchema {
	private static final Logger log = Logger.getLogger(RouteDestination.class.getName());

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!RouteDestination.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'RouteDestination' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<DestinationCIDRv4> adapterDestinationCIDRv4 =
					gson.getDelegateAdapter(this, TypeToken.get(DestinationCIDRv4.class));
			final TypeAdapter<DestinationCIDRv6> adapterDestinationCIDRv6 =
					gson.getDelegateAdapter(this, TypeToken.get(DestinationCIDRv6.class));

			return (TypeAdapter<T>)
					new TypeAdapter<RouteDestination>() {
						@Override
						public void write(JsonWriter out, RouteDestination value)
								throws IOException {
							if (value == null || value.getActualInstance() == null) {
								elementAdapter.write(out, null);
								return;
							}

							// check if the actual instance is of the type `DestinationCIDRv4`
							if (value.getActualInstance() instanceof DestinationCIDRv4) {
								JsonElement element =
										adapterDestinationCIDRv4.toJsonTree(
												(DestinationCIDRv4) value.getActualInstance());
								elementAdapter.write(out, element);
								return;
							}
							// check if the actual instance is of the type `DestinationCIDRv6`
							if (value.getActualInstance() instanceof DestinationCIDRv6) {
								JsonElement element =
										adapterDestinationCIDRv6.toJsonTree(
												(DestinationCIDRv6) value.getActualInstance());
								elementAdapter.write(out, element);
								return;
							}
							throw new IOException(
									"Failed to serialize as the type doesn't match oneOf schemas: DestinationCIDRv4, DestinationCIDRv6");
						}

						@Override
						public RouteDestination read(JsonReader in) throws IOException {
							Object deserialized = null;
							JsonElement jsonElement = elementAdapter.read(in);

							int match = 0;
							ArrayList<String> errorMessages = new ArrayList<>();
							TypeAdapter actualAdapter = elementAdapter;

							// deserialize DestinationCIDRv4
							try {
								// validate the JSON object to see if any exception is thrown
								DestinationCIDRv4.validateJsonElement(jsonElement);
								actualAdapter = adapterDestinationCIDRv4;
								match++;
								log.log(
										Level.FINER,
										"Input data matches schema 'DestinationCIDRv4'");
							} catch (Exception e) {
								// deserialization failed, continue
								errorMessages.add(
										String.format(
												"Deserialization for DestinationCIDRv4 failed with `%s`.",
												e.getMessage()));
								log.log(
										Level.FINER,
										"Input data does not match schema 'DestinationCIDRv4'",
										e);
							}
							// deserialize DestinationCIDRv6
							try {
								// validate the JSON object to see if any exception is thrown
								DestinationCIDRv6.validateJsonElement(jsonElement);
								actualAdapter = adapterDestinationCIDRv6;
								match++;
								log.log(
										Level.FINER,
										"Input data matches schema 'DestinationCIDRv6'");
							} catch (Exception e) {
								// deserialization failed, continue
								errorMessages.add(
										String.format(
												"Deserialization for DestinationCIDRv6 failed with `%s`.",
												e.getMessage()));
								log.log(
										Level.FINER,
										"Input data does not match schema 'DestinationCIDRv6'",
										e);
							}

							if (match == 1) {
								RouteDestination ret = new RouteDestination();
								ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
								return ret;
							}

							throw new IOException(
									String.format(
											"Failed deserialization for RouteDestination: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s",
											match, errorMessages, jsonElement.toString()));
						}
					}.nullSafe();
		}
	}

	// store a list of schema names defined in oneOf
	public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

	public RouteDestination() {
		super("oneOf", Boolean.FALSE);
	}

	public RouteDestination(Object o) {
		super("oneOf", Boolean.FALSE);
		setActualInstance(o);
	}

	static {
		schemas.put("DestinationCIDRv4", DestinationCIDRv4.class);
		schemas.put("DestinationCIDRv6", DestinationCIDRv6.class);
	}

	@Override
	public Map<String, Class<?>> getSchemas() {
		return RouteDestination.schemas;
	}

	/**
	 * Set the instance that matches the oneOf child schema, check the instance parameter is valid
	 * against the oneOf child schemas: DestinationCIDRv4, DestinationCIDRv6
	 *
	 * <p>It could be an instance of the 'oneOf' schemas.
	 */
	@Override
	public void setActualInstance(Object instance) {
		if (instance instanceof DestinationCIDRv4) {
			super.setActualInstance(instance);
			return;
		}

		if (instance instanceof DestinationCIDRv6) {
			super.setActualInstance(instance);
			return;
		}

		throw new RuntimeException(
				"Invalid instance type. Must be DestinationCIDRv4, DestinationCIDRv6");
	}

	/**
	 * Get the actual instance, which can be the following: DestinationCIDRv4, DestinationCIDRv6
	 *
	 * @return The actual instance (DestinationCIDRv4, DestinationCIDRv6)
	 */
	@SuppressWarnings("unchecked")
	@Override
	public Object getActualInstance() {
		return super.getActualInstance();
	}

	/**
	 * Get the actual instance of `DestinationCIDRv4`. If the actual instance is not
	 * `DestinationCIDRv4`, the ClassCastException will be thrown.
	 *
	 * @return The actual instance of `DestinationCIDRv4`
	 * @throws ClassCastException if the instance is not `DestinationCIDRv4`
	 */
	public DestinationCIDRv4 getDestinationCIDRv4() throws ClassCastException {
		return (DestinationCIDRv4) super.getActualInstance();
	}

	/**
	 * Get the actual instance of `DestinationCIDRv6`. If the actual instance is not
	 * `DestinationCIDRv6`, the ClassCastException will be thrown.
	 *
	 * @return The actual instance of `DestinationCIDRv6`
	 * @throws ClassCastException if the instance is not `DestinationCIDRv6`
	 */
	public DestinationCIDRv6 getDestinationCIDRv6() throws ClassCastException {
		return (DestinationCIDRv6) super.getActualInstance();
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to RouteDestination
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		// validate oneOf schemas one by one
		int validCount = 0;
		ArrayList<String> errorMessages = new ArrayList<>();
		// validate the json string with DestinationCIDRv4
		try {
			DestinationCIDRv4.validateJsonElement(jsonElement);
			validCount++;
		} catch (Exception e) {
			errorMessages.add(
					String.format(
							"Deserialization for DestinationCIDRv4 failed with `%s`.",
							e.getMessage()));
			// continue to the next one
		}
		// validate the json string with DestinationCIDRv6
		try {
			DestinationCIDRv6.validateJsonElement(jsonElement);
			validCount++;
		} catch (Exception e) {
			errorMessages.add(
					String.format(
							"Deserialization for DestinationCIDRv6 failed with `%s`.",
							e.getMessage()));
			// continue to the next one
		}
		if (validCount != 1) {
			throw new IOException(
					String.format(
							"The JSON string is invalid for RouteDestination with oneOf schemas: DestinationCIDRv4, DestinationCIDRv6. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s",
							validCount, errorMessages, jsonElement.toString()));
		}
	}

	/**
	 * Create an instance of RouteDestination given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of RouteDestination
	 * @throws IOException if the JSON string is invalid with respect to RouteDestination
	 */
	public static RouteDestination fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, RouteDestination.class);
	}

	/**
	 * Convert an instance of RouteDestination to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
