/*
 * IaaS-API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.model;

import cloud.stackit.sdk.iaas.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** The internet protocol which the rule matches. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class SecurityGroupRuleProtocol {
	public static final String SERIALIZED_NAME_PROTOCOL = "protocol";

	@SerializedName(SERIALIZED_NAME_PROTOCOL)
	@javax.annotation.Nullable private Protocol protocol;

	public SecurityGroupRuleProtocol() {}

	public SecurityGroupRuleProtocol protocol(@javax.annotation.Nullable Protocol protocol) {
		this.protocol = protocol;
		return this;
	}

	/**
	 * Get protocol
	 *
	 * @return protocol
	 */
	@javax.annotation.Nullable public Protocol getProtocol() {
		return protocol;
	}

	public void setProtocol(@javax.annotation.Nullable Protocol protocol) {
		this.protocol = protocol;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SecurityGroupRuleProtocol securityGroupRuleProtocol = (SecurityGroupRuleProtocol) o;
		return Objects.equals(this.protocol, securityGroupRuleProtocol.protocol);
	}

	@Override
	public int hashCode() {
		return Objects.hash(protocol);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SecurityGroupRuleProtocol {\n");
		sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("protocol"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to SecurityGroupRuleProtocol
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!SecurityGroupRuleProtocol.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in SecurityGroupRuleProtocol is not found in the empty JSON string",
								SecurityGroupRuleProtocol.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!SecurityGroupRuleProtocol.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `SecurityGroupRuleProtocol` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// validate the optional field `protocol`
		if (jsonObj.get("protocol") != null && !jsonObj.get("protocol").isJsonNull()) {
			Protocol.validateJsonElement(jsonObj.get("protocol"));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!SecurityGroupRuleProtocol.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'SecurityGroupRuleProtocol' and its
				// subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<SecurityGroupRuleProtocol> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(SecurityGroupRuleProtocol.class));

			return (TypeAdapter<T>)
					new TypeAdapter<SecurityGroupRuleProtocol>() {
						@Override
						public void write(JsonWriter out, SecurityGroupRuleProtocol value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public SecurityGroupRuleProtocol read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of SecurityGroupRuleProtocol given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of SecurityGroupRuleProtocol
	 * @throws IOException if the JSON string is invalid with respect to SecurityGroupRuleProtocol
	 */
	public static SecurityGroupRuleProtocol fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, SecurityGroupRuleProtocol.class);
	}

	/**
	 * Convert an instance of SecurityGroupRuleProtocol to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
