/*
 * IaaS-API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2beta1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.model;

import cloud.stackit.sdk.iaas.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Object that represents an update request body of an Image. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class UpdateImagePayload {
	public static final String SERIALIZED_NAME_AGENT = "agent";

	@SerializedName(SERIALIZED_NAME_AGENT)
	@javax.annotation.Nullable private ImageAgent agent;

	public static final String SERIALIZED_NAME_CONFIG = "config";

	@SerializedName(SERIALIZED_NAME_CONFIG)
	@javax.annotation.Nullable private ImageConfig config;

	public static final String SERIALIZED_NAME_DISK_FORMAT = "diskFormat";

	@SerializedName(SERIALIZED_NAME_DISK_FORMAT)
	@javax.annotation.Nullable private String diskFormat;

	public static final String SERIALIZED_NAME_LABELS = "labels";

	@SerializedName(SERIALIZED_NAME_LABELS)
	@javax.annotation.Nullable private Object labels;

	public static final String SERIALIZED_NAME_MIN_DISK_SIZE = "minDiskSize";

	@SerializedName(SERIALIZED_NAME_MIN_DISK_SIZE)
	@javax.annotation.Nullable private Long minDiskSize;

	public static final String SERIALIZED_NAME_MIN_RAM = "minRam";

	@SerializedName(SERIALIZED_NAME_MIN_RAM)
	@javax.annotation.Nullable private Long minRam;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	@javax.annotation.Nullable private String name;

	public static final String SERIALIZED_NAME_PROTECTED = "protected";

	@SerializedName(SERIALIZED_NAME_PROTECTED)
	@javax.annotation.Nullable private Boolean _protected;

	public UpdateImagePayload() {}

	public UpdateImagePayload agent(@javax.annotation.Nullable ImageAgent agent) {
		this.agent = agent;
		return this;
	}

	/**
	 * Get agent
	 *
	 * @return agent
	 */
	@javax.annotation.Nullable public ImageAgent getAgent() {
		return agent;
	}

	public void setAgent(@javax.annotation.Nullable ImageAgent agent) {
		this.agent = agent;
	}

	public UpdateImagePayload config(@javax.annotation.Nullable ImageConfig config) {
		this.config = config;
		return this;
	}

	/**
	 * Get config
	 *
	 * @return config
	 */
	@javax.annotation.Nullable public ImageConfig getConfig() {
		return config;
	}

	public void setConfig(@javax.annotation.Nullable ImageConfig config) {
		this.config = config;
	}

	public UpdateImagePayload diskFormat(@javax.annotation.Nullable String diskFormat) {
		this.diskFormat = diskFormat;
		return this;
	}

	/**
	 * Object that represents a disk format. Possible values: &#x60;raw&#x60;, &#x60;qcow2&#x60;,
	 * &#x60;iso&#x60;.
	 *
	 * @return diskFormat
	 */
	@javax.annotation.Nullable public String getDiskFormat() {
		return diskFormat;
	}

	public void setDiskFormat(@javax.annotation.Nullable String diskFormat) {
		this.diskFormat = diskFormat;
	}

	public UpdateImagePayload labels(@javax.annotation.Nullable Object labels) {
		this.labels = labels;
		return this;
	}

	/**
	 * Object that represents the labels of an object. Regex for keys:
	 * &#x60;^(?&#x3D;.{1,63}$)([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$&#x60;. Regex for values:
	 * &#x60;^(?&#x3D;.{0,63}$)(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])*$&#x60;. Providing a
	 * &#x60;null&#x60; value for a key will remove that key.
	 *
	 * @return labels
	 */
	@javax.annotation.Nullable public Object getLabels() {
		return labels;
	}

	public void setLabels(@javax.annotation.Nullable Object labels) {
		this.labels = labels;
	}

	public UpdateImagePayload minDiskSize(@javax.annotation.Nullable Long minDiskSize) {
		this.minDiskSize = minDiskSize;
		return this;
	}

	/**
	 * Size in Gigabyte.
	 *
	 * @return minDiskSize
	 */
	@javax.annotation.Nullable public Long getMinDiskSize() {
		return minDiskSize;
	}

	public void setMinDiskSize(@javax.annotation.Nullable Long minDiskSize) {
		this.minDiskSize = minDiskSize;
	}

	public UpdateImagePayload minRam(@javax.annotation.Nullable Long minRam) {
		this.minRam = minRam;
		return this;
	}

	/**
	 * Size in Megabyte.
	 *
	 * @return minRam
	 */
	@javax.annotation.Nullable public Long getMinRam() {
		return minRam;
	}

	public void setMinRam(@javax.annotation.Nullable Long minRam) {
		this.minRam = minRam;
	}

	public UpdateImagePayload name(@javax.annotation.Nullable String name) {
		this.name = name;
		return this;
	}

	/**
	 * The name for a General Object. Matches Names and also UUIDs.
	 *
	 * @return name
	 */
	@javax.annotation.Nullable public String getName() {
		return name;
	}

	public void setName(@javax.annotation.Nullable String name) {
		this.name = name;
	}

	public UpdateImagePayload _protected(@javax.annotation.Nullable Boolean _protected) {
		this._protected = _protected;
		return this;
	}

	/**
	 * When true the image is prevented from being deleted.
	 *
	 * @return _protected
	 */
	@javax.annotation.Nullable public Boolean getProtected() {
		return _protected;
	}

	public void setProtected(@javax.annotation.Nullable Boolean _protected) {
		this._protected = _protected;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		UpdateImagePayload updateImagePayload = (UpdateImagePayload) o;
		return Objects.equals(this.agent, updateImagePayload.agent)
				&& Objects.equals(this.config, updateImagePayload.config)
				&& Objects.equals(this.diskFormat, updateImagePayload.diskFormat)
				&& Objects.equals(this.labels, updateImagePayload.labels)
				&& Objects.equals(this.minDiskSize, updateImagePayload.minDiskSize)
				&& Objects.equals(this.minRam, updateImagePayload.minRam)
				&& Objects.equals(this.name, updateImagePayload.name)
				&& Objects.equals(this._protected, updateImagePayload._protected);
	}

	@Override
	public int hashCode() {
		return Objects.hash(
				agent, config, diskFormat, labels, minDiskSize, minRam, name, _protected);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class UpdateImagePayload {\n");
		sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
		sb.append("    config: ").append(toIndentedString(config)).append("\n");
		sb.append("    diskFormat: ").append(toIndentedString(diskFormat)).append("\n");
		sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
		sb.append("    minDiskSize: ").append(toIndentedString(minDiskSize)).append("\n");
		sb.append("    minRam: ").append(toIndentedString(minRam)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    _protected: ").append(toIndentedString(_protected)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields =
				new HashSet<String>(
						Arrays.asList(
								"agent",
								"config",
								"diskFormat",
								"labels",
								"minDiskSize",
								"minRam",
								"name",
								"protected"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to UpdateImagePayload
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!UpdateImagePayload.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in UpdateImagePayload is not found in the empty JSON string",
								UpdateImagePayload.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!UpdateImagePayload.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `UpdateImagePayload` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// validate the optional field `agent`
		if (jsonObj.get("agent") != null && !jsonObj.get("agent").isJsonNull()) {
			ImageAgent.validateJsonElement(jsonObj.get("agent"));
		}
		// validate the optional field `config`
		if (jsonObj.get("config") != null && !jsonObj.get("config").isJsonNull()) {
			ImageConfig.validateJsonElement(jsonObj.get("config"));
		}
		if ((jsonObj.get("diskFormat") != null && !jsonObj.get("diskFormat").isJsonNull())
				&& !jsonObj.get("diskFormat").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							"Expected the field `diskFormat` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("diskFormat").toString()));
		}
		if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull())
				&& !jsonObj.get("name").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							"Expected the field `name` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("name").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!UpdateImagePayload.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'UpdateImagePayload' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<UpdateImagePayload> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(UpdateImagePayload.class));

			return (TypeAdapter<T>)
					new TypeAdapter<UpdateImagePayload>() {
						@Override
						public void write(JsonWriter out, UpdateImagePayload value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public UpdateImagePayload read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of UpdateImagePayload given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of UpdateImagePayload
	 * @throws IOException if the JSON string is invalid with respect to UpdateImagePayload
	 */
	public static UpdateImagePayload fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, UpdateImagePayload.class);
	}

	/**
	 * Convert an instance of UpdateImagePayload to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
