/*
 * STACKIT Object Storage API
 * STACKIT API to manage the Object Storage
 *
 * The version of the OpenAPI document: 2.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.objectstorage.model;

import cloud.stackit.sdk.objectstorage.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** DeleteAccessKeyResponse */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class DeleteAccessKeyResponse {
	public static final String SERIALIZED_NAME_KEY_ID = "keyId";

	@SerializedName(SERIALIZED_NAME_KEY_ID)
	@javax.annotation.Nonnull
	private String keyId;

	public static final String SERIALIZED_NAME_PROJECT = "project";

	@SerializedName(SERIALIZED_NAME_PROJECT)
	@javax.annotation.Nonnull
	private String project;

	public DeleteAccessKeyResponse() {}

	public DeleteAccessKeyResponse keyId(@javax.annotation.Nonnull String keyId) {
		this.keyId = keyId;
		return this;
	}

	/**
	 * Identifies the pair of access key and secret access key for deletion
	 *
	 * @return keyId
	 */
	@javax.annotation.Nonnull
	public String getKeyId() {
		return keyId;
	}

	public void setKeyId(@javax.annotation.Nonnull String keyId) {
		this.keyId = keyId;
	}

	public DeleteAccessKeyResponse project(@javax.annotation.Nonnull String project) {
		this.project = project;
		return this;
	}

	/**
	 * Project ID
	 *
	 * @return project
	 */
	@javax.annotation.Nonnull
	public String getProject() {
		return project;
	}

	public void setProject(@javax.annotation.Nonnull String project) {
		this.project = project;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		DeleteAccessKeyResponse deleteAccessKeyResponse = (DeleteAccessKeyResponse) o;
		return Objects.equals(this.keyId, deleteAccessKeyResponse.keyId)
				&& Objects.equals(this.project, deleteAccessKeyResponse.project);
	}

	@Override
	public int hashCode() {
		return Objects.hash(keyId, project);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class DeleteAccessKeyResponse {\n");
		sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
		sb.append("    project: ").append(toIndentedString(project)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("keyId", "project"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(Arrays.asList("keyId", "project"));
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to DeleteAccessKeyResponse
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!DeleteAccessKeyResponse.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in DeleteAccessKeyResponse is not found in the empty JSON string",
								DeleteAccessKeyResponse.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!DeleteAccessKeyResponse.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The field `%s` in the JSON string is not defined in the `DeleteAccessKeyResponse` properties. JSON: %s",
								entry.getKey(),
								jsonElement.toString()));
			}
		}

		// check to make sure all required properties/fields are present in the JSON string
		for (String requiredField : DeleteAccessKeyResponse.openapiRequiredFields) {
			if (jsonElement.getAsJsonObject().get(requiredField) == null) {
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field `%s` is not found in the JSON string: %s",
								requiredField,
								jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		if (!jsonObj.get("keyId").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `keyId` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("keyId").toString()));
		}
		if (!jsonObj.get("project").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `project` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("project").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!DeleteAccessKeyResponse.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'DeleteAccessKeyResponse' and its
				// subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<DeleteAccessKeyResponse> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(DeleteAccessKeyResponse.class));

			return (TypeAdapter<T>)
					new TypeAdapter<DeleteAccessKeyResponse>() {
						@Override
						public void write(JsonWriter out, DeleteAccessKeyResponse value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public DeleteAccessKeyResponse read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of DeleteAccessKeyResponse given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of DeleteAccessKeyResponse
	 * @throws IOException if the JSON string is invalid with respect to DeleteAccessKeyResponse
	 */
	public static DeleteAccessKeyResponse fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, DeleteAccessKeyResponse.class);
	}

	/**
	 * Convert an instance of DeleteAccessKeyResponse to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
