/*
 * STACKIT Object Storage API
 * STACKIT API to manage the Object Storage
 *
 * The version of the OpenAPI document: 2.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.objectstorage.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * The scope of a STACKIT project can be public (default) or can have client specific special
 * requirements.
 */
@JsonAdapter(ProjectScope.Adapter.class)
public enum ProjectScope {
	PUBLIC("PUBLIC"),

	SCHWARZ("SCHWARZ"),

	UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

	private String value;

	ProjectScope(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return String.valueOf(value);
	}

	public static ProjectScope fromValue(String value) {
		for (ProjectScope b : ProjectScope.values()) {
			if (b.value.equals(value)) {
				return b;
			}
		}
		return UNKNOWN_DEFAULT_OPEN_API;
	}

	public static class Adapter extends TypeAdapter<ProjectScope> {
		@Override
		public void write(final JsonWriter jsonWriter, final ProjectScope enumeration)
				throws IOException {
			jsonWriter.value(enumeration.getValue());
		}

		@Override
		public ProjectScope read(final JsonReader jsonReader) throws IOException {
			String value = jsonReader.nextString();
			return ProjectScope.fromValue(value);
		}
	}

	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		String value = jsonElement.getAsString();
		ProjectScope.fromValue(value);
	}
}
