/*
 * STACKIT File Storage (SFS)
 * API used to create and manage NFS Shares.
 *
 * The version of the OpenAPI document: 1beta.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.sfs.model;

import cloud.stackit.sdk.sfs.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** ResourcePool */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class ResourcePool {
	public static final String SERIALIZED_NAME_AVAILABILITY_ZONE = "availabilityZone";

	@SerializedName(SERIALIZED_NAME_AVAILABILITY_ZONE)
	@javax.annotation.Nullable private String availabilityZone;

	public static final String SERIALIZED_NAME_COUNT_SHARES = "countShares";

	@SerializedName(SERIALIZED_NAME_COUNT_SHARES)
	@javax.annotation.Nullable private Integer countShares;

	public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";

	@SerializedName(SERIALIZED_NAME_CREATED_AT)
	@javax.annotation.Nullable private OffsetDateTime createdAt;

	public static final String SERIALIZED_NAME_ID = "id";

	@SerializedName(SERIALIZED_NAME_ID)
	@javax.annotation.Nullable private String id;

	public static final String SERIALIZED_NAME_IP_ACL = "ipAcl";

	@SerializedName(SERIALIZED_NAME_IP_ACL)
	@javax.annotation.Nullable private List<String> ipAcl = new ArrayList<>();

	public static final String SERIALIZED_NAME_LABELS = "labels";

	@SerializedName(SERIALIZED_NAME_LABELS)
	@javax.annotation.Nullable private Map<String, String> labels = new HashMap<>();

	public static final String SERIALIZED_NAME_MOUNT_PATH = "mountPath";

	@SerializedName(SERIALIZED_NAME_MOUNT_PATH)
	@javax.annotation.Nullable private String mountPath;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	@javax.annotation.Nullable private String name;

	public static final String SERIALIZED_NAME_PERFORMANCE_CLASS = "performanceClass";

	@SerializedName(SERIALIZED_NAME_PERFORMANCE_CLASS)
	@javax.annotation.Nullable private ResourcePoolPerformanceClass performanceClass;

	public static final String SERIALIZED_NAME_PERFORMANCE_CLASS_DOWNGRADABLE_AT =
			"performanceClassDowngradableAt";

	@SerializedName(SERIALIZED_NAME_PERFORMANCE_CLASS_DOWNGRADABLE_AT)
	@javax.annotation.Nullable private OffsetDateTime performanceClassDowngradableAt;

	public static final String SERIALIZED_NAME_SIZE_REDUCIBLE_AT = "sizeReducibleAt";

	@SerializedName(SERIALIZED_NAME_SIZE_REDUCIBLE_AT)
	@javax.annotation.Nullable private OffsetDateTime sizeReducibleAt;

	public static final String SERIALIZED_NAME_SNAPSHOT_SCHEDULE = "snapshotSchedule";

	@SerializedName(SERIALIZED_NAME_SNAPSHOT_SCHEDULE)
	@javax.annotation.Nullable private SnapshotSchedule snapshotSchedule;

	public static final String SERIALIZED_NAME_SNAPSHOTS_ARE_VISIBLE = "snapshotsAreVisible";

	@SerializedName(SERIALIZED_NAME_SNAPSHOTS_ARE_VISIBLE)
	@javax.annotation.Nullable private Boolean snapshotsAreVisible;

	public static final String SERIALIZED_NAME_SPACE = "space";

	@SerializedName(SERIALIZED_NAME_SPACE)
	@javax.annotation.Nullable private ResourcePoolSpace space;

	public static final String SERIALIZED_NAME_STATE = "state";

	@SerializedName(SERIALIZED_NAME_STATE)
	@javax.annotation.Nullable private String state;

	public ResourcePool() {}

	public ResourcePool availabilityZone(@javax.annotation.Nullable String availabilityZone) {
		this.availabilityZone = availabilityZone;
		return this;
	}

	/**
	 * Name of the respective availability zone
	 *
	 * @return availabilityZone
	 */
	@javax.annotation.Nullable public String getAvailabilityZone() {
		return availabilityZone;
	}

	public void setAvailabilityZone(@javax.annotation.Nullable String availabilityZone) {
		this.availabilityZone = availabilityZone;
	}

	public ResourcePool countShares(@javax.annotation.Nullable Integer countShares) {
		this.countShares = countShares;
		return this;
	}

	/**
	 * Number of Shares in the Resource Pool
	 *
	 * @return countShares
	 */
	@javax.annotation.Nullable public Integer getCountShares() {
		return countShares;
	}

	public void setCountShares(@javax.annotation.Nullable Integer countShares) {
		this.countShares = countShares;
	}

	public ResourcePool createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
		this.createdAt = createdAt;
		return this;
	}

	/**
	 * Get createdAt
	 *
	 * @return createdAt
	 */
	@javax.annotation.Nullable public OffsetDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public ResourcePool id(@javax.annotation.Nullable String id) {
		this.id = id;
		return this;
	}

	/**
	 * ID of the Resource Pool
	 *
	 * @return id
	 */
	@javax.annotation.Nullable public String getId() {
		return id;
	}

	public void setId(@javax.annotation.Nullable String id) {
		this.id = id;
	}

	public ResourcePool ipAcl(@javax.annotation.Nullable List<String> ipAcl) {
		this.ipAcl = ipAcl;
		return this;
	}

	public ResourcePool addIpAclItem(String ipAclItem) {
		if (this.ipAcl == null) {
			this.ipAcl = new ArrayList<>();
		}
		this.ipAcl.add(ipAclItem);
		return this;
	}

	/**
	 * List of IPs that can mount the Resource Pool in read-only; IPs must have a subnet mask (e.g.
	 * \&quot;172.16.0.0/24\&quot; for a range of IPs, or \&quot;172.16.0.250/32\&quot; for a
	 * specific IP)
	 *
	 * @return ipAcl
	 */
	@javax.annotation.Nullable public List<String> getIpAcl() {
		return ipAcl;
	}

	public void setIpAcl(@javax.annotation.Nullable List<String> ipAcl) {
		this.ipAcl = ipAcl;
	}

	public ResourcePool labels(@javax.annotation.Nullable Map<String, String> labels) {
		this.labels = labels;
		return this;
	}

	public ResourcePool putLabelsItem(String key, String labelsItem) {
		if (this.labels == null) {
			this.labels = new HashMap<>();
		}
		this.labels.put(key, labelsItem);
		return this;
	}

	/**
	 * Get labels
	 *
	 * @return labels
	 */
	@javax.annotation.Nullable public Map<String, String> getLabels() {
		return labels;
	}

	public void setLabels(@javax.annotation.Nullable Map<String, String> labels) {
		this.labels = labels;
	}

	public ResourcePool mountPath(@javax.annotation.Nullable String mountPath) {
		this.mountPath = mountPath;
		return this;
	}

	/**
	 * Mount path of the Resource Pool, used to mount the Resource Pool Note that a Resource Pool
	 * can only be mounted in read-only
	 *
	 * @return mountPath
	 */
	@javax.annotation.Nullable public String getMountPath() {
		return mountPath;
	}

	public void setMountPath(@javax.annotation.Nullable String mountPath) {
		this.mountPath = mountPath;
	}

	public ResourcePool name(@javax.annotation.Nullable String name) {
		this.name = name;
		return this;
	}

	/**
	 * Name of the Resource Pool
	 *
	 * @return name
	 */
	@javax.annotation.Nullable public String getName() {
		return name;
	}

	public void setName(@javax.annotation.Nullable String name) {
		this.name = name;
	}

	public ResourcePool performanceClass(
			@javax.annotation.Nullable ResourcePoolPerformanceClass performanceClass) {
		this.performanceClass = performanceClass;
		return this;
	}

	/**
	 * Information about the performance class
	 *
	 * @return performanceClass
	 */
	@javax.annotation.Nullable public ResourcePoolPerformanceClass getPerformanceClass() {
		return performanceClass;
	}

	public void setPerformanceClass(
			@javax.annotation.Nullable ResourcePoolPerformanceClass performanceClass) {
		this.performanceClass = performanceClass;
	}

	public ResourcePool performanceClassDowngradableAt(
			@javax.annotation.Nullable OffsetDateTime performanceClassDowngradableAt) {
		this.performanceClassDowngradableAt = performanceClassDowngradableAt;
		return this;
	}

	/**
	 * Time when the performance class can be downgraded again.
	 *
	 * @return performanceClassDowngradableAt
	 */
	@javax.annotation.Nullable public OffsetDateTime getPerformanceClassDowngradableAt() {
		return performanceClassDowngradableAt;
	}

	public void setPerformanceClassDowngradableAt(
			@javax.annotation.Nullable OffsetDateTime performanceClassDowngradableAt) {
		this.performanceClassDowngradableAt = performanceClassDowngradableAt;
	}

	public ResourcePool sizeReducibleAt(@javax.annotation.Nullable OffsetDateTime sizeReducibleAt) {
		this.sizeReducibleAt = sizeReducibleAt;
		return this;
	}

	/**
	 * Time when the size can be reduced again.
	 *
	 * @return sizeReducibleAt
	 */
	@javax.annotation.Nullable public OffsetDateTime getSizeReducibleAt() {
		return sizeReducibleAt;
	}

	public void setSizeReducibleAt(@javax.annotation.Nullable OffsetDateTime sizeReducibleAt) {
		this.sizeReducibleAt = sizeReducibleAt;
	}

	public ResourcePool snapshotSchedule(
			@javax.annotation.Nullable SnapshotSchedule snapshotSchedule) {
		this.snapshotSchedule = snapshotSchedule;
		return this;
	}

	/**
	 * Get snapshotSchedule
	 *
	 * @return snapshotSchedule
	 */
	@javax.annotation.Nullable public SnapshotSchedule getSnapshotSchedule() {
		return snapshotSchedule;
	}

	public void setSnapshotSchedule(@javax.annotation.Nullable SnapshotSchedule snapshotSchedule) {
		this.snapshotSchedule = snapshotSchedule;
	}

	public ResourcePool snapshotsAreVisible(
			@javax.annotation.Nullable Boolean snapshotsAreVisible) {
		this.snapshotsAreVisible = snapshotsAreVisible;
		return this;
	}

	/**
	 * Whether the .snapshot directory is visible when mounting the resource pool. Setting this
	 * value to false might prevent you from accessing the snapshots (e.g. for security reasons).
	 * Additionally, the access to the snapshots is always controlled by the export policy of the
	 * resource pool. That means, if snapshots are visible and the export policy allows for reading
	 * the resource pool, then it also allows reading the snapshot of all shares.
	 *
	 * @return snapshotsAreVisible
	 */
	@javax.annotation.Nullable public Boolean getSnapshotsAreVisible() {
		return snapshotsAreVisible;
	}

	public void setSnapshotsAreVisible(@javax.annotation.Nullable Boolean snapshotsAreVisible) {
		this.snapshotsAreVisible = snapshotsAreVisible;
	}

	public ResourcePool space(@javax.annotation.Nullable ResourcePoolSpace space) {
		this.space = space;
		return this;
	}

	/**
	 * Space information
	 *
	 * @return space
	 */
	@javax.annotation.Nullable public ResourcePoolSpace getSpace() {
		return space;
	}

	public void setSpace(@javax.annotation.Nullable ResourcePoolSpace space) {
		this.space = space;
	}

	public ResourcePool state(@javax.annotation.Nullable String state) {
		this.state = state;
		return this;
	}

	/**
	 * State of the Resource Pool (possible values: [\&quot;pending\&quot;, \&quot;creating\&quot;,
	 * \&quot;created\&quot;, \&quot;updating\&quot;, \&quot;error\&quot;, \&quot;deleting\&quot;])
	 *
	 * @return state
	 */
	@javax.annotation.Nullable public String getState() {
		return state;
	}

	public void setState(@javax.annotation.Nullable String state) {
		this.state = state;
	}

	/**
	 * A container for additional, undeclared properties. This is a holder for any undeclared
	 * properties as specified with the 'additionalProperties' keyword in the OAS document.
	 */
	private Map<String, Object> additionalProperties;

	/**
	 * Set the additional (undeclared) property with the specified name and value. If the property
	 * does not already exist, create it otherwise replace it.
	 *
	 * @param key name of the property
	 * @param value value of the property
	 * @return the ResourcePool instance itself
	 */
	public ResourcePool putAdditionalProperty(String key, Object value) {
		if (this.additionalProperties == null) {
			this.additionalProperties = new HashMap<String, Object>();
		}
		this.additionalProperties.put(key, value);
		return this;
	}

	/**
	 * Return the additional (undeclared) property.
	 *
	 * @return a map of objects
	 */
	public Map<String, Object> getAdditionalProperties() {
		return additionalProperties;
	}

	/**
	 * Return the additional (undeclared) property with the specified name.
	 *
	 * @param key name of the property
	 * @return an object
	 */
	public Object getAdditionalProperty(String key) {
		if (this.additionalProperties == null) {
			return null;
		}
		return this.additionalProperties.get(key);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ResourcePool resourcePool = (ResourcePool) o;
		return Objects.equals(this.availabilityZone, resourcePool.availabilityZone)
				&& Objects.equals(this.countShares, resourcePool.countShares)
				&& Objects.equals(this.createdAt, resourcePool.createdAt)
				&& Objects.equals(this.id, resourcePool.id)
				&& Objects.equals(this.ipAcl, resourcePool.ipAcl)
				&& Objects.equals(this.labels, resourcePool.labels)
				&& Objects.equals(this.mountPath, resourcePool.mountPath)
				&& Objects.equals(this.name, resourcePool.name)
				&& Objects.equals(this.performanceClass, resourcePool.performanceClass)
				&& Objects.equals(
						this.performanceClassDowngradableAt,
						resourcePool.performanceClassDowngradableAt)
				&& Objects.equals(this.sizeReducibleAt, resourcePool.sizeReducibleAt)
				&& Objects.equals(this.snapshotSchedule, resourcePool.snapshotSchedule)
				&& Objects.equals(this.snapshotsAreVisible, resourcePool.snapshotsAreVisible)
				&& Objects.equals(this.space, resourcePool.space)
				&& Objects.equals(this.state, resourcePool.state)
				&& Objects.equals(this.additionalProperties, resourcePool.additionalProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(
				availabilityZone,
				countShares,
				createdAt,
				id,
				ipAcl,
				labels,
				mountPath,
				name,
				performanceClass,
				performanceClassDowngradableAt,
				sizeReducibleAt,
				snapshotSchedule,
				snapshotsAreVisible,
				space,
				state,
				additionalProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ResourcePool {\n");
		sb.append("    availabilityZone: ").append(toIndentedString(availabilityZone)).append("\n");
		sb.append("    countShares: ").append(toIndentedString(countShares)).append("\n");
		sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    ipAcl: ").append(toIndentedString(ipAcl)).append("\n");
		sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
		sb.append("    mountPath: ").append(toIndentedString(mountPath)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    performanceClass: ").append(toIndentedString(performanceClass)).append("\n");
		sb.append("    performanceClassDowngradableAt: ")
				.append(toIndentedString(performanceClassDowngradableAt))
				.append("\n");
		sb.append("    sizeReducibleAt: ").append(toIndentedString(sizeReducibleAt)).append("\n");
		sb.append("    snapshotSchedule: ").append(toIndentedString(snapshotSchedule)).append("\n");
		sb.append("    snapshotsAreVisible: ")
				.append(toIndentedString(snapshotsAreVisible))
				.append("\n");
		sb.append("    space: ").append(toIndentedString(space)).append("\n");
		sb.append("    state: ").append(toIndentedString(state)).append("\n");
		sb.append("    additionalProperties: ")
				.append(toIndentedString(additionalProperties))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields =
				new HashSet<String>(
						Arrays.asList(
								"availabilityZone",
								"countShares",
								"createdAt",
								"id",
								"ipAcl",
								"labels",
								"mountPath",
								"name",
								"performanceClass",
								"performanceClassDowngradableAt",
								"sizeReducibleAt",
								"snapshotSchedule",
								"snapshotsAreVisible",
								"space",
								"state"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to ResourcePool
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!ResourcePool.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in ResourcePool is not found in the empty JSON string",
								ResourcePool.openapiRequiredFields.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		if ((jsonObj.get("availabilityZone") != null
						&& !jsonObj.get("availabilityZone").isJsonNull())
				&& !jsonObj.get("availabilityZone").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `availabilityZone` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("availabilityZone").toString()));
		}
		if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull())
				&& !jsonObj.get("id").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `id` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("id").toString()));
		}
		// ensure the optional json data is an array if present
		if (jsonObj.get("ipAcl") != null
				&& !jsonObj.get("ipAcl").isJsonNull()
				&& !jsonObj.get("ipAcl").isJsonArray()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `ipAcl` to be an array in the JSON string but got `%s`",
							jsonObj.get("ipAcl").toString()));
		}
		if ((jsonObj.get("mountPath") != null && !jsonObj.get("mountPath").isJsonNull())
				&& !jsonObj.get("mountPath").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `mountPath` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("mountPath").toString()));
		}
		if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull())
				&& !jsonObj.get("name").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `name` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("name").toString()));
		}
		// validate the optional field `performanceClass`
		if (jsonObj.get("performanceClass") != null
				&& !jsonObj.get("performanceClass").isJsonNull()) {
			ResourcePoolPerformanceClass.validateJsonElement(jsonObj.get("performanceClass"));
		}
		// validate the optional field `snapshotSchedule`
		if (jsonObj.get("snapshotSchedule") != null
				&& !jsonObj.get("snapshotSchedule").isJsonNull()) {
			SnapshotSchedule.validateJsonElement(jsonObj.get("snapshotSchedule"));
		}
		// validate the optional field `space`
		if (jsonObj.get("space") != null && !jsonObj.get("space").isJsonNull()) {
			ResourcePoolSpace.validateJsonElement(jsonObj.get("space"));
		}
		if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull())
				&& !jsonObj.get("state").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `state` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("state").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!ResourcePool.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'ResourcePool' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<ResourcePool> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(ResourcePool.class));

			return (TypeAdapter<T>)
					new TypeAdapter<ResourcePool>() {
						@Override
						public void write(JsonWriter out, ResourcePool value) throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							obj.remove("additionalProperties");
							// serialize additional properties
							if (value.getAdditionalProperties() != null) {
								for (Map.Entry<String, Object> entry :
										value.getAdditionalProperties().entrySet()) {
									if (entry.getValue() instanceof String)
										obj.addProperty(entry.getKey(), (String) entry.getValue());
									else if (entry.getValue() instanceof Number)
										obj.addProperty(entry.getKey(), (Number) entry.getValue());
									else if (entry.getValue() instanceof Boolean)
										obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
									else if (entry.getValue() instanceof Character)
										obj.addProperty(
												entry.getKey(), (Character) entry.getValue());
									else {
										JsonElement jsonElement = gson.toJsonTree(entry.getValue());
										if (jsonElement.isJsonArray()) {
											obj.add(entry.getKey(), jsonElement.getAsJsonArray());
										} else {
											obj.add(entry.getKey(), jsonElement.getAsJsonObject());
										}
									}
								}
							}
							elementAdapter.write(out, obj);
						}

						@Override
						public ResourcePool read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							JsonObject jsonObj = jsonElement.getAsJsonObject();
							// store additional fields in the deserialized instance
							ResourcePool instance = thisAdapter.fromJsonTree(jsonObj);
							for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
								if (!openapiFields.contains(entry.getKey())) {
									if (entry.getValue().isJsonPrimitive()) { // primitive type
										if (entry.getValue().getAsJsonPrimitive().isString())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsString());
										else if (entry.getValue().getAsJsonPrimitive().isNumber())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsNumber());
										else if (entry.getValue().getAsJsonPrimitive().isBoolean())
											instance.putAdditionalProperty(
													entry.getKey(),
													entry.getValue().getAsBoolean());
										else
											throw new IllegalArgumentException(
													String.format(
															java.util.Locale.ROOT,
															"The field `%s` has unknown primitive type. Value: %s",
															entry.getKey(),
															entry.getValue().toString()));
									} else if (entry.getValue().isJsonArray()) {
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), List.class));
									} else { // JSON object
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), HashMap.class));
									}
								}
							}
							return instance;
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of ResourcePool given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of ResourcePool
	 * @throws IOException if the JSON string is invalid with respect to ResourcePool
	 */
	public static ResourcePool fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, ResourcePool.class);
	}

	/**
	 * Convert an instance of ResourcePool to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
