/*
 * STACKIT Network Load Balancer API
 * This API offers an interface to provision and manage load balancing servers in your STACKIT project. It also has the possibility of pooling target servers for load balancing purposes.  For each load balancer provided, two VMs are deployed in your OpenStack project subject to a fee.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.loadbalancer.model;

import cloud.stackit.sdk.loadbalancer.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Use this option to limit the IP ranges that can use the load balancer. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.19.0")
public class LoadbalancerOptionAccessControl {
	public static final String SERIALIZED_NAME_ALLOWED_SOURCE_RANGES = "allowedSourceRanges";

	@SerializedName(SERIALIZED_NAME_ALLOWED_SOURCE_RANGES)
	@javax.annotation.Nullable private List<String> allowedSourceRanges = new ArrayList<>();

	public LoadbalancerOptionAccessControl() {}

	public LoadbalancerOptionAccessControl allowedSourceRanges(
			@javax.annotation.Nullable List<String> allowedSourceRanges) {
		this.allowedSourceRanges = allowedSourceRanges;
		return this;
	}

	public LoadbalancerOptionAccessControl addAllowedSourceRangesItem(
			String allowedSourceRangesItem) {
		if (this.allowedSourceRanges == null) {
			this.allowedSourceRanges = new ArrayList<>();
		}
		this.allowedSourceRanges.add(allowedSourceRangesItem);
		return this;
	}

	/**
	 * Load Balancer is accessible only from an IP address in this range
	 *
	 * @return allowedSourceRanges
	 */
	@javax.annotation.Nullable public List<String> getAllowedSourceRanges() {
		return allowedSourceRanges;
	}

	public void setAllowedSourceRanges(
			@javax.annotation.Nullable List<String> allowedSourceRanges) {
		this.allowedSourceRanges = allowedSourceRanges;
	}

	/**
	 * A container for additional, undeclared properties. This is a holder for any undeclared
	 * properties as specified with the 'additionalProperties' keyword in the OAS document.
	 */
	private Map<String, Object> additionalProperties;

	/**
	 * Set the additional (undeclared) property with the specified name and value. If the property
	 * does not already exist, create it otherwise replace it.
	 *
	 * @param key name of the property
	 * @param value value of the property
	 * @return the LoadbalancerOptionAccessControl instance itself
	 */
	public LoadbalancerOptionAccessControl putAdditionalProperty(String key, Object value) {
		if (this.additionalProperties == null) {
			this.additionalProperties = new HashMap<String, Object>();
		}
		this.additionalProperties.put(key, value);
		return this;
	}

	/**
	 * Return the additional (undeclared) property.
	 *
	 * @return a map of objects
	 */
	public Map<String, Object> getAdditionalProperties() {
		return additionalProperties;
	}

	/**
	 * Return the additional (undeclared) property with the specified name.
	 *
	 * @param key name of the property
	 * @return an object
	 */
	public Object getAdditionalProperty(String key) {
		if (this.additionalProperties == null) {
			return null;
		}
		return this.additionalProperties.get(key);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		LoadbalancerOptionAccessControl loadbalancerOptionAccessControl =
				(LoadbalancerOptionAccessControl) o;
		return Objects.equals(
						this.allowedSourceRanges,
						loadbalancerOptionAccessControl.allowedSourceRanges)
				&& Objects.equals(
						this.additionalProperties,
						loadbalancerOptionAccessControl.additionalProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(allowedSourceRanges, additionalProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LoadbalancerOptionAccessControl {\n");
		sb.append("    allowedSourceRanges: ")
				.append(toIndentedString(allowedSourceRanges))
				.append("\n");
		sb.append("    additionalProperties: ")
				.append(toIndentedString(additionalProperties))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("allowedSourceRanges"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to
	 *     LoadbalancerOptionAccessControl
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!LoadbalancerOptionAccessControl.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in LoadbalancerOptionAccessControl is not found in the empty JSON string",
								LoadbalancerOptionAccessControl.openapiRequiredFields.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// ensure the optional json data is an array if present
		if (jsonObj.get("allowedSourceRanges") != null
				&& !jsonObj.get("allowedSourceRanges").isJsonNull()
				&& !jsonObj.get("allowedSourceRanges").isJsonArray()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `allowedSourceRanges` to be an array in the JSON string but got `%s`",
							jsonObj.get("allowedSourceRanges").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!LoadbalancerOptionAccessControl.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'LoadbalancerOptionAccessControl' and its
				// subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<LoadbalancerOptionAccessControl> thisAdapter =
					gson.getDelegateAdapter(
							this, TypeToken.get(LoadbalancerOptionAccessControl.class));

			return (TypeAdapter<T>)
					new TypeAdapter<LoadbalancerOptionAccessControl>() {
						@Override
						public void write(JsonWriter out, LoadbalancerOptionAccessControl value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							obj.remove("additionalProperties");
							// serialize additional properties
							if (value.getAdditionalProperties() != null) {
								for (Map.Entry<String, Object> entry :
										value.getAdditionalProperties().entrySet()) {
									if (entry.getValue() instanceof String)
										obj.addProperty(entry.getKey(), (String) entry.getValue());
									else if (entry.getValue() instanceof Number)
										obj.addProperty(entry.getKey(), (Number) entry.getValue());
									else if (entry.getValue() instanceof Boolean)
										obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
									else if (entry.getValue() instanceof Character)
										obj.addProperty(
												entry.getKey(), (Character) entry.getValue());
									else {
										JsonElement jsonElement = gson.toJsonTree(entry.getValue());
										if (jsonElement.isJsonArray()) {
											obj.add(entry.getKey(), jsonElement.getAsJsonArray());
										} else {
											obj.add(entry.getKey(), jsonElement.getAsJsonObject());
										}
									}
								}
							}
							elementAdapter.write(out, obj);
						}

						@Override
						public LoadbalancerOptionAccessControl read(JsonReader in)
								throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							JsonObject jsonObj = jsonElement.getAsJsonObject();
							// store additional fields in the deserialized instance
							LoadbalancerOptionAccessControl instance =
									thisAdapter.fromJsonTree(jsonObj);
							for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
								if (!openapiFields.contains(entry.getKey())) {
									if (entry.getValue().isJsonPrimitive()) { // primitive type
										if (entry.getValue().getAsJsonPrimitive().isString())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsString());
										else if (entry.getValue().getAsJsonPrimitive().isNumber())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsNumber());
										else if (entry.getValue().getAsJsonPrimitive().isBoolean())
											instance.putAdditionalProperty(
													entry.getKey(),
													entry.getValue().getAsBoolean());
										else
											throw new IllegalArgumentException(
													String.format(
															java.util.Locale.ROOT,
															"The field `%s` has unknown primitive type. Value: %s",
															entry.getKey(),
															entry.getValue().toString()));
									} else if (entry.getValue().isJsonArray()) {
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), List.class));
									} else { // JSON object
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), HashMap.class));
									}
								}
							}
							return instance;
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of LoadbalancerOptionAccessControl given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of LoadbalancerOptionAccessControl
	 * @throws IOException if the JSON string is invalid with respect to
	 *     LoadbalancerOptionAccessControl
	 */
	public static LoadbalancerOptionAccessControl fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, LoadbalancerOptionAccessControl.class);
	}

	/**
	 * Convert an instance of LoadbalancerOptionAccessControl to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
