/*
 * STACKIT Network Load Balancer API
 * This API offers an interface to provision and manage load balancing servers in your STACKIT project. It also has the possibility of pooling target servers for load balancing purposes.  For each load balancer provided, two VMs are deployed in your OpenStack project subject to a fee.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.loadbalancer.model;

import cloud.stackit.sdk.loadbalancer.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** UpdateCredentialsResponse */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class UpdateCredentialsResponse {
	public static final String SERIALIZED_NAME_CREDENTIAL = "credential";

	@SerializedName(SERIALIZED_NAME_CREDENTIAL)
	@javax.annotation.Nullable private CredentialsResponse credential;

	public UpdateCredentialsResponse() {}

	public UpdateCredentialsResponse credential(
			@javax.annotation.Nullable CredentialsResponse credential) {
		this.credential = credential;
		return this;
	}

	/**
	 * Get credential
	 *
	 * @return credential
	 */
	@javax.annotation.Nullable public CredentialsResponse getCredential() {
		return credential;
	}

	public void setCredential(@javax.annotation.Nullable CredentialsResponse credential) {
		this.credential = credential;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		UpdateCredentialsResponse updateCredentialsResponse = (UpdateCredentialsResponse) o;
		return Objects.equals(this.credential, updateCredentialsResponse.credential);
	}

	@Override
	public int hashCode() {
		return Objects.hash(credential);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class UpdateCredentialsResponse {\n");
		sb.append("    credential: ").append(toIndentedString(credential)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("credential"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(0);
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to UpdateCredentialsResponse
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!UpdateCredentialsResponse.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								"The required field(s) %s in UpdateCredentialsResponse is not found in the empty JSON string",
								UpdateCredentialsResponse.openapiRequiredFields.toString()));
			}
		}

		Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
		// check to see if the JSON string contains additional fields
		for (Map.Entry<String, JsonElement> entry : entries) {
			if (!UpdateCredentialsResponse.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(
						String.format(
								"The field `%s` in the JSON string is not defined in the `UpdateCredentialsResponse` properties. JSON: %s",
								entry.getKey(), jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// validate the optional field `credential`
		if (jsonObj.get("credential") != null && !jsonObj.get("credential").isJsonNull()) {
			CredentialsResponse.validateJsonElement(jsonObj.get("credential"));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!UpdateCredentialsResponse.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'UpdateCredentialsResponse' and its
				// subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<UpdateCredentialsResponse> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(UpdateCredentialsResponse.class));

			return (TypeAdapter<T>)
					new TypeAdapter<UpdateCredentialsResponse>() {
						@Override
						public void write(JsonWriter out, UpdateCredentialsResponse value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							elementAdapter.write(out, obj);
						}

						@Override
						public UpdateCredentialsResponse read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							return thisAdapter.fromJsonTree(jsonElement);
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of UpdateCredentialsResponse given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of UpdateCredentialsResponse
	 * @throws IOException if the JSON string is invalid with respect to UpdateCredentialsResponse
	 */
	public static UpdateCredentialsResponse fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, UpdateCredentialsResponse.class);
	}

	/**
	 * Convert an instance of UpdateCredentialsResponse to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
