/*
 * STACKIT File Storage (SFS)
 * API used to create and manage NFS Shares.
 *
 * The version of the OpenAPI document: 1beta.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.sfs;

import java.util.HashSet;

/** Representing a Server Variable for server URL template substitution. */
@javax.annotation.Generated(
		value = "org.openapitools.codegen.languages.JavaClientCodegen",
		comments = "Generator version: 7.15.0")
public class ServerVariable {
	public String description;
	public String defaultValue;
	public HashSet<String> enumValues = null;

	/**
	 * @param description A description for the server variable.
	 * @param defaultValue The default value to use for substitution.
	 * @param enumValues An enumeration of string values to be used if the substitution options are
	 *     from a limited set.
	 */
	public ServerVariable(String description, String defaultValue, HashSet<String> enumValues) {
		this.description = description;
		this.defaultValue = defaultValue;
		this.enumValues = enumValues;
	}
}
