/*
 * STACKIT IaaS API
 * This API is deprecated. It will be retired on 01.03.2027. Please use the STACKIT IaaS API V2 instead.
 *
 * The version of the OpenAPI document: 1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.iaas.v1api.api;

import cloud.stackit.sdk.core.config.CoreConfiguration;
import java.io.IOException;
import okhttp3.OkHttpClient;

public class IaasApi extends DefaultApi {
	/**
	 * Basic constructor for IaasApi
	 *
	 * <p>For production use consider using the constructor with the OkHttpClient parameter.
	 *
	 * @throws IOException
	 */
	public IaasApi() throws IOException {
		super();
	}

	/**
	 * Basic Constructor for IaasApi
	 *
	 * <p>For production use consider using the constructor with the OkHttpClient parameter.
	 *
	 * @param configuration your STACKIT SDK CoreConfiguration
	 * @throws IOException
	 */
	public IaasApi(CoreConfiguration configuration) throws IOException {
		super(configuration);
	}

	/**
	 * Constructor for IaasApi
	 *
	 * @param httpClient OkHttpClient object
	 * @throws IOException
	 */
	public IaasApi(OkHttpClient httpClient) throws IOException {
		super(httpClient);
	}

	/**
	 * Constructor for IaasApi
	 *
	 * @param httpClient OkHttpClient object
	 * @param configuration your STACKIT SDK CoreConfiguration
	 * @throws IOException
	 */
	public IaasApi(OkHttpClient httpClient, CoreConfiguration configuration) throws IOException {
		super(httpClient, configuration);
	}
}
