/*
 * STACKIT Automation Service API
 * API endpoints for automation management .
 *
 * The version of the OpenAPI document: 1beta.0
 * Contact: support@stackit.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.automation.v1betaapi.api;

import cloud.stackit.sdk.automation.v1betaapi.ApiCallback;
import cloud.stackit.sdk.automation.v1betaapi.ApiClient;
import cloud.stackit.sdk.automation.v1betaapi.ApiResponse;
import cloud.stackit.sdk.automation.v1betaapi.Pair;
import cloud.stackit.sdk.automation.v1betaapi.model.CreateVolumeAutomationPayload;
import cloud.stackit.sdk.automation.v1betaapi.model.GetVolumeTemplateResponse;
import cloud.stackit.sdk.automation.v1betaapi.model.ListAutomationsResponse;
import cloud.stackit.sdk.automation.v1betaapi.model.ListExecutionsResponse;
import cloud.stackit.sdk.automation.v1betaapi.model.ListTemplatesResponse;
import cloud.stackit.sdk.automation.v1betaapi.model.PartialUpdateVolumeAutomationPayload;
import cloud.stackit.sdk.automation.v1betaapi.model.VolumeAutomation;
import cloud.stackit.sdk.automation.v1betaapi.model.VolumeExecutionResponse;
import cloud.stackit.sdk.core.config.CoreConfiguration;
import cloud.stackit.sdk.core.exception.ApiException;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import okhttp3.OkHttpClient;

// Package-private access to enforce service-specific API usage (DefaultApi => <ServiceName>Api)
class DefaultApi {
	private ApiClient localVarApiClient;
	private int localHostIndex;
	private String localCustomBaseUrl;

	/**
	 * Basic constructor for DefaultApi
	 *
	 * <p>For production use consider using the constructor with the OkHttpClient parameter.
	 *
	 * @throws IOException
	 */
	public DefaultApi() throws IOException {
		this(null, new CoreConfiguration());
	}

	/**
	 * Basic Constructor for DefaultApi
	 *
	 * <p>For production use consider using the constructor with the OkHttpClient parameter.
	 *
	 * @param config your STACKIT SDK CoreConfiguration
	 * @throws IOException
	 */
	public DefaultApi(CoreConfiguration config) throws IOException {
		this(null, config);
	}

	/**
	 * Constructor for DefaultApi
	 *
	 * @param httpClient OkHttpClient object
	 * @throws IOException
	 */
	public DefaultApi(OkHttpClient httpClient) throws IOException {
		this(httpClient, new CoreConfiguration());
	}

	/**
	 * Constructor for DefaultApi
	 *
	 * @param httpClient OkHttpClient object
	 * @param config your STACKIT SDK CoreConfiguration
	 * @throws IOException
	 */
	public DefaultApi(OkHttpClient httpClient, CoreConfiguration config) throws IOException {
		if (config.getCustomEndpoint() != null && !config.getCustomEndpoint().trim().isEmpty()) {
			localCustomBaseUrl = config.getCustomEndpoint();
		}
		this.localVarApiClient = new ApiClient(httpClient, config);
	}

	public ApiClient getApiClient() {
		return localVarApiClient;
	}

	public void setApiClient(ApiClient apiClient) {
		this.localVarApiClient = apiClient;
	}

	public int getHostIndex() {
		return localHostIndex;
	}

	public void setHostIndex(int hostIndex) {
		this.localHostIndex = hostIndex;
	}

	public String getCustomBaseUrl() {
		return localCustomBaseUrl;
	}

	public void setCustomBaseUrl(String customBaseUrl) {
		this.localCustomBaseUrl = customBaseUrl;
	}

	/**
	 * Build call for createVolumeAutomation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param createVolumeAutomationPayload (optional)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 201 </td><td> Automation created </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call createVolumeAutomationCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable CreateVolumeAutomationPayload createVolumeAutomationPayload,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = createVolumeAutomationPayload;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {"application/json"};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"POST",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call createVolumeAutomationValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable CreateVolumeAutomationPayload createVolumeAutomationPayload,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling createVolumeAutomation(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling createVolumeAutomation(Async)");
		}

		return createVolumeAutomationCall(
				projectId, region, createVolumeAutomationPayload, _callback);
	}

	/**
	 * Create volume automation Creates a new volume automation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param createVolumeAutomationPayload (optional)
	 * @return VolumeAutomation
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 201 </td><td> Automation created </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public VolumeAutomation createVolumeAutomation(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable CreateVolumeAutomationPayload createVolumeAutomationPayload)
			throws ApiException {
		ApiResponse<VolumeAutomation> localVarResp =
				createVolumeAutomationWithHttpInfo(
						projectId, region, createVolumeAutomationPayload);
		return localVarResp.getData();
	}

	/**
	 * Create volume automation Creates a new volume automation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param createVolumeAutomationPayload (optional)
	 * @return ApiResponse&lt;VolumeAutomation&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 201 </td><td> Automation created </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<VolumeAutomation> createVolumeAutomationWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable CreateVolumeAutomationPayload createVolumeAutomationPayload)
			throws ApiException {
		okhttp3.Call localVarCall =
				createVolumeAutomationValidateBeforeCall(
						projectId, region, createVolumeAutomationPayload, null);
		Type localVarReturnType = new TypeToken<VolumeAutomation>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * Create volume automation (asynchronously) Creates a new volume automation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param createVolumeAutomationPayload (optional)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 201 </td><td> Automation created </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call createVolumeAutomationAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable CreateVolumeAutomationPayload createVolumeAutomationPayload,
			final ApiCallback<VolumeAutomation> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				createVolumeAutomationValidateBeforeCall(
						projectId, region, createVolumeAutomationPayload, _callback);
		Type localVarReturnType = new TypeToken<VolumeAutomation>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for createVolumeExecution
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 201 </td><td> Automation created </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call createVolumeExecutionCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations/{automationId}/executions"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()))
						.replace(
								"{" + "automationId" + "}",
								localVarApiClient.escapeString(automationId.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"POST",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call createVolumeExecutionValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling createVolumeExecution(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling createVolumeExecution(Async)");
		}

		// verify the required parameter 'automationId' is set
		if (automationId == null) {
			throw new ApiException(
					"Missing the required parameter 'automationId' when calling createVolumeExecution(Async)");
		}

		return createVolumeExecutionCall(projectId, region, automationId, _callback);
	}

	/**
	 * Create volume automation executions Creates a new execution for a specific volume automation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @return VolumeExecutionResponse
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 201 </td><td> Automation created </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public VolumeExecutionResponse createVolumeExecution(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId)
			throws ApiException {
		ApiResponse<VolumeExecutionResponse> localVarResp =
				createVolumeExecutionWithHttpInfo(projectId, region, automationId);
		return localVarResp.getData();
	}

	/**
	 * Create volume automation executions Creates a new execution for a specific volume automation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @return ApiResponse&lt;VolumeExecutionResponse&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 201 </td><td> Automation created </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<VolumeExecutionResponse> createVolumeExecutionWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId)
			throws ApiException {
		okhttp3.Call localVarCall =
				createVolumeExecutionValidateBeforeCall(projectId, region, automationId, null);
		Type localVarReturnType = new TypeToken<VolumeExecutionResponse>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * Create volume automation executions (asynchronously) Creates a new execution for a specific
	 * volume automation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 201 </td><td> Automation created </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call createVolumeExecutionAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback<VolumeExecutionResponse> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				createVolumeExecutionValidateBeforeCall(projectId, region, automationId, _callback);
		Type localVarReturnType = new TypeToken<VolumeExecutionResponse>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for deleteVolumeAutomation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 204 </td><td> automation deleted </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call deleteVolumeAutomationCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations/{automationId}"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()))
						.replace(
								"{" + "automationId" + "}",
								localVarApiClient.escapeString(automationId.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"DELETE",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call deleteVolumeAutomationValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling deleteVolumeAutomation(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling deleteVolumeAutomation(Async)");
		}

		// verify the required parameter 'automationId' is set
		if (automationId == null) {
			throw new ApiException(
					"Missing the required parameter 'automationId' when calling deleteVolumeAutomation(Async)");
		}

		return deleteVolumeAutomationCall(projectId, region, automationId, _callback);
	}

	/**
	 * Delete volume automation Deletes a specific volume automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 204 </td><td> automation deleted </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public void deleteVolumeAutomation(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId)
			throws ApiException {
		deleteVolumeAutomationWithHttpInfo(projectId, region, automationId);
	}

	/**
	 * Delete volume automation Deletes a specific volume automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @return ApiResponse&lt;Void&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 204 </td><td> automation deleted </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<Void> deleteVolumeAutomationWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId)
			throws ApiException {
		okhttp3.Call localVarCall =
				deleteVolumeAutomationValidateBeforeCall(projectId, region, automationId, null);
		return localVarApiClient.execute(localVarCall);
	}

	/**
	 * Delete volume automation (asynchronously) Deletes a specific volume automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 204 </td><td> automation deleted </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call deleteVolumeAutomationAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback<Void> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				deleteVolumeAutomationValidateBeforeCall(
						projectId, region, automationId, _callback);
		localVarApiClient.executeAsync(localVarCall, _callback);
		return localVarCall;
	}

	/**
	 * Build call for getVolumeAutomation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automation details </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call getVolumeAutomationCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations/{automationId}"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()))
						.replace(
								"{" + "automationId" + "}",
								localVarApiClient.escapeString(automationId.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"GET",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call getVolumeAutomationValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling getVolumeAutomation(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling getVolumeAutomation(Async)");
		}

		// verify the required parameter 'automationId' is set
		if (automationId == null) {
			throw new ApiException(
					"Missing the required parameter 'automationId' when calling getVolumeAutomation(Async)");
		}

		return getVolumeAutomationCall(projectId, region, automationId, _callback);
	}

	/**
	 * Get volume automation Retrieves a specific volume automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @return VolumeAutomation
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automation details </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public VolumeAutomation getVolumeAutomation(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId)
			throws ApiException {
		ApiResponse<VolumeAutomation> localVarResp =
				getVolumeAutomationWithHttpInfo(projectId, region, automationId);
		return localVarResp.getData();
	}

	/**
	 * Get volume automation Retrieves a specific volume automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @return ApiResponse&lt;VolumeAutomation&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automation details </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<VolumeAutomation> getVolumeAutomationWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId)
			throws ApiException {
		okhttp3.Call localVarCall =
				getVolumeAutomationValidateBeforeCall(projectId, region, automationId, null);
		Type localVarReturnType = new TypeToken<VolumeAutomation>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * Get volume automation (asynchronously) Retrieves a specific volume automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automation details </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call getVolumeAutomationAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			final ApiCallback<VolumeAutomation> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				getVolumeAutomationValidateBeforeCall(projectId, region, automationId, _callback);
		Type localVarReturnType = new TypeToken<VolumeAutomation>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for getVolumeExecution
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param executionId execution Id (required)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call getVolumeExecutionCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nonnull String executionId,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations/{automationId}/executions/{executionId}"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()))
						.replace(
								"{" + "automationId" + "}",
								localVarApiClient.escapeString(automationId.toString()))
						.replace(
								"{" + "executionId" + "}",
								localVarApiClient.escapeString(executionId.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"GET",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call getVolumeExecutionValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nonnull String executionId,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling getVolumeExecution(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling getVolumeExecution(Async)");
		}

		// verify the required parameter 'automationId' is set
		if (automationId == null) {
			throw new ApiException(
					"Missing the required parameter 'automationId' when calling getVolumeExecution(Async)");
		}

		// verify the required parameter 'executionId' is set
		if (executionId == null) {
			throw new ApiException(
					"Missing the required parameter 'executionId' when calling getVolumeExecution(Async)");
		}

		return getVolumeExecutionCall(projectId, region, automationId, executionId, _callback);
	}

	/**
	 * Get volume automation execution details Get details for a specific volume automation
	 * execution
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param executionId execution Id (required)
	 * @return VolumeExecutionResponse
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public VolumeExecutionResponse getVolumeExecution(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nonnull String executionId)
			throws ApiException {
		ApiResponse<VolumeExecutionResponse> localVarResp =
				getVolumeExecutionWithHttpInfo(projectId, region, automationId, executionId);
		return localVarResp.getData();
	}

	/**
	 * Get volume automation execution details Get details for a specific volume automation
	 * execution
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param executionId execution Id (required)
	 * @return ApiResponse&lt;VolumeExecutionResponse&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<VolumeExecutionResponse> getVolumeExecutionWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nonnull String executionId)
			throws ApiException {
		okhttp3.Call localVarCall =
				getVolumeExecutionValidateBeforeCall(
						projectId, region, automationId, executionId, null);
		Type localVarReturnType = new TypeToken<VolumeExecutionResponse>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * Get volume automation execution details (asynchronously) Get details for a specific volume
	 * automation execution
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param executionId execution Id (required)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call getVolumeExecutionAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nonnull String executionId,
			final ApiCallback<VolumeExecutionResponse> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				getVolumeExecutionValidateBeforeCall(
						projectId, region, automationId, executionId, _callback);
		Type localVarReturnType = new TypeToken<VolumeExecutionResponse>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for getVolumeTemplate
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param templateId templateId Id (required)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> template get response details </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call getVolumeTemplateCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String templateId,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations/templates/{templateId}"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()))
						.replace(
								"{" + "templateId" + "}",
								localVarApiClient.escapeString(templateId.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"GET",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call getVolumeTemplateValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String templateId,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling getVolumeTemplate(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling getVolumeTemplate(Async)");
		}

		// verify the required parameter 'templateId' is set
		if (templateId == null) {
			throw new ApiException(
					"Missing the required parameter 'templateId' when calling getVolumeTemplate(Async)");
		}

		return getVolumeTemplateCall(projectId, region, templateId, _callback);
	}

	/**
	 * Get volume template Retrieve detailed information about a volume template
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param templateId templateId Id (required)
	 * @return GetVolumeTemplateResponse
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> template get response details </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public GetVolumeTemplateResponse getVolumeTemplate(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String templateId)
			throws ApiException {
		ApiResponse<GetVolumeTemplateResponse> localVarResp =
				getVolumeTemplateWithHttpInfo(projectId, region, templateId);
		return localVarResp.getData();
	}

	/**
	 * Get volume template Retrieve detailed information about a volume template
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param templateId templateId Id (required)
	 * @return ApiResponse&lt;GetVolumeTemplateResponse&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> template get response details </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<GetVolumeTemplateResponse> getVolumeTemplateWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String templateId)
			throws ApiException {
		okhttp3.Call localVarCall =
				getVolumeTemplateValidateBeforeCall(projectId, region, templateId, null);
		Type localVarReturnType = new TypeToken<GetVolumeTemplateResponse>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * Get volume template (asynchronously) Retrieve detailed information about a volume template
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param templateId templateId Id (required)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> template get response details </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call getVolumeTemplateAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String templateId,
			final ApiCallback<GetVolumeTemplateResponse> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				getVolumeTemplateValidateBeforeCall(projectId, region, templateId, _callback);
		Type localVarReturnType = new TypeToken<GetVolumeTemplateResponse>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for listVolumeAutomations
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call listVolumeAutomationsCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		if (pageSize != null) {
			localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
		}

		if (pageToken != null) {
			localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageToken", pageToken));
		}

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"GET",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call listVolumeAutomationsValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling listVolumeAutomations(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling listVolumeAutomations(Async)");
		}

		return listVolumeAutomationsCall(projectId, region, pageSize, pageToken, _callback);
	}

	/**
	 * List volume automations Retrieves a list of volume automations.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @return ListAutomationsResponse
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ListAutomationsResponse listVolumeAutomations(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken)
			throws ApiException {
		ApiResponse<ListAutomationsResponse> localVarResp =
				listVolumeAutomationsWithHttpInfo(projectId, region, pageSize, pageToken);
		return localVarResp.getData();
	}

	/**
	 * List volume automations Retrieves a list of volume automations.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @return ApiResponse&lt;ListAutomationsResponse&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<ListAutomationsResponse> listVolumeAutomationsWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken)
			throws ApiException {
		okhttp3.Call localVarCall =
				listVolumeAutomationsValidateBeforeCall(
						projectId, region, pageSize, pageToken, null);
		Type localVarReturnType = new TypeToken<ListAutomationsResponse>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * List volume automations (asynchronously) Retrieves a list of volume automations.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call listVolumeAutomationsAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback<ListAutomationsResponse> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				listVolumeAutomationsValidateBeforeCall(
						projectId, region, pageSize, pageToken, _callback);
		Type localVarReturnType = new TypeToken<ListAutomationsResponse>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for listVolumeExecutions
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call listVolumeExecutionsCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations/{automationId}/executions"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()))
						.replace(
								"{" + "automationId" + "}",
								localVarApiClient.escapeString(automationId.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		if (pageSize != null) {
			localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
		}

		if (pageToken != null) {
			localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageToken", pageToken));
		}

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"GET",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call listVolumeExecutionsValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling listVolumeExecutions(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling listVolumeExecutions(Async)");
		}

		// verify the required parameter 'automationId' is set
		if (automationId == null) {
			throw new ApiException(
					"Missing the required parameter 'automationId' when calling listVolumeExecutions(Async)");
		}

		return listVolumeExecutionsCall(
				projectId, region, automationId, pageSize, pageToken, _callback);
	}

	/**
	 * List volume automation executions Get a list of all executions for a specific volume
	 * automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @return ListExecutionsResponse
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ListExecutionsResponse listVolumeExecutions(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken)
			throws ApiException {
		ApiResponse<ListExecutionsResponse> localVarResp =
				listVolumeExecutionsWithHttpInfo(
						projectId, region, automationId, pageSize, pageToken);
		return localVarResp.getData();
	}

	/**
	 * List volume automation executions Get a list of all executions for a specific volume
	 * automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @return ApiResponse&lt;ListExecutionsResponse&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<ListExecutionsResponse> listVolumeExecutionsWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken)
			throws ApiException {
		okhttp3.Call localVarCall =
				listVolumeExecutionsValidateBeforeCall(
						projectId, region, automationId, pageSize, pageToken, null);
		Type localVarReturnType = new TypeToken<ListExecutionsResponse>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * List volume automation executions (asynchronously) Get a list of all executions for a
	 * specific volume automation.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automations list </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call listVolumeExecutionsAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback<ListExecutionsResponse> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				listVolumeExecutionsValidateBeforeCall(
						projectId, region, automationId, pageSize, pageToken, _callback);
		Type localVarReturnType = new TypeToken<ListExecutionsResponse>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for listVolumeTemplates
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> template list response </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call listVolumeTemplatesCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations/templates"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		if (pageSize != null) {
			localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
		}

		if (pageToken != null) {
			localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageToken", pageToken));
		}

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"GET",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call listVolumeTemplatesValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling listVolumeTemplates(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling listVolumeTemplates(Async)");
		}

		return listVolumeTemplatesCall(projectId, region, pageSize, pageToken, _callback);
	}

	/**
	 * List volume templates Lists all volume templates for the specified service
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @return ListTemplatesResponse
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> template list response </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ListTemplatesResponse listVolumeTemplates(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken)
			throws ApiException {
		ApiResponse<ListTemplatesResponse> localVarResp =
				listVolumeTemplatesWithHttpInfo(projectId, region, pageSize, pageToken);
		return localVarResp.getData();
	}

	/**
	 * List volume templates Lists all volume templates for the specified service
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @return ApiResponse&lt;ListTemplatesResponse&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> template list response </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<ListTemplatesResponse> listVolumeTemplatesWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken)
			throws ApiException {
		okhttp3.Call localVarCall =
				listVolumeTemplatesValidateBeforeCall(projectId, region, pageSize, pageToken, null);
		Type localVarReturnType = new TypeToken<ListTemplatesResponse>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * List volume templates (asynchronously) Lists all volume templates for the specified service
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param pageSize The maximum number of items to return. If unspecified or set to 0, at most
	 *     100 items will be returned. The maximum value is 100; values above 100 will be coerced to
	 *     100. (optional, default to 100)
	 * @param pageToken A page token, received from a previous list call. Provide this to retrieve
	 *     the subsequent page. (optional)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> template list response </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call listVolumeTemplatesAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nullable Integer pageSize,
			@javax.annotation.Nullable String pageToken,
			final ApiCallback<ListTemplatesResponse> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				listVolumeTemplatesValidateBeforeCall(
						projectId, region, pageSize, pageToken, _callback);
		Type localVarReturnType = new TypeToken<ListTemplatesResponse>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for partialUpdateVolumeAutomation
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param updateMask A comma-separated list of fully qualified names of fields to be updated.
	 *     Example: \&quot;name,triggers.schedule.rrule\&quot; (optional)
	 * @param partialUpdateVolumeAutomationPayload (optional)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automation updated </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call partialUpdateVolumeAutomationCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable String updateMask,
			@javax.annotation.Nullable PartialUpdateVolumeAutomationPayload partialUpdateVolumeAutomationPayload,
			final ApiCallback _callback)
			throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		} else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		} else {
			basePath = null;
		}

		Object localVarPostBody = partialUpdateVolumeAutomationPayload;

		// create path and map variables
		String localVarPath =
				"/v1beta/projects/{projectId}/regions/{region}/services/volumes/automations/{automationId}"
						.replace(
								"{" + "projectId" + "}",
								localVarApiClient.escapeString(projectId.toString()))
						.replace(
								"{" + "region" + "}",
								localVarApiClient.escapeString(region.toString()))
						.replace(
								"{" + "automationId" + "}",
								localVarApiClient.escapeString(automationId.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		if (updateMask != null) {
			localVarQueryParams.addAll(localVarApiClient.parameterToPair("updateMask", updateMask));
		}

		final String[] localVarAccepts = {"application/json"};
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {"application/json"};
		final String localVarContentType =
				localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(
				basePath,
				localVarPath,
				"PATCH",
				localVarQueryParams,
				localVarCollectionQueryParams,
				localVarPostBody,
				localVarHeaderParams,
				localVarCookieParams,
				localVarFormParams,
				localVarAuthNames,
				_callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call partialUpdateVolumeAutomationValidateBeforeCall(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable String updateMask,
			@javax.annotation.Nullable PartialUpdateVolumeAutomationPayload partialUpdateVolumeAutomationPayload,
			final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'projectId' is set
		if (projectId == null) {
			throw new ApiException(
					"Missing the required parameter 'projectId' when calling partialUpdateVolumeAutomation(Async)");
		}

		// verify the required parameter 'region' is set
		if (region == null) {
			throw new ApiException(
					"Missing the required parameter 'region' when calling partialUpdateVolumeAutomation(Async)");
		}

		// verify the required parameter 'automationId' is set
		if (automationId == null) {
			throw new ApiException(
					"Missing the required parameter 'automationId' when calling partialUpdateVolumeAutomation(Async)");
		}

		return partialUpdateVolumeAutomationCall(
				projectId,
				region,
				automationId,
				updateMask,
				partialUpdateVolumeAutomationPayload,
				_callback);
	}

	/**
	 * Patch volume automation Partially updates a specific volume automation. Specify the fields to
	 * update in the &#x60;updateMask&#x60; query parameter.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param updateMask A comma-separated list of fully qualified names of fields to be updated.
	 *     Example: \&quot;name,triggers.schedule.rrule\&quot; (optional)
	 * @param partialUpdateVolumeAutomationPayload (optional)
	 * @return VolumeAutomation
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automation updated </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public VolumeAutomation partialUpdateVolumeAutomation(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable String updateMask,
			@javax.annotation.Nullable PartialUpdateVolumeAutomationPayload partialUpdateVolumeAutomationPayload)
			throws ApiException {
		ApiResponse<VolumeAutomation> localVarResp =
				partialUpdateVolumeAutomationWithHttpInfo(
						projectId,
						region,
						automationId,
						updateMask,
						partialUpdateVolumeAutomationPayload);
		return localVarResp.getData();
	}

	/**
	 * Patch volume automation Partially updates a specific volume automation. Specify the fields to
	 * update in the &#x60;updateMask&#x60; query parameter.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param updateMask A comma-separated list of fully qualified names of fields to be updated.
	 *     Example: \&quot;name,triggers.schedule.rrule\&quot; (optional)
	 * @param partialUpdateVolumeAutomationPayload (optional)
	 * @return ApiResponse&lt;VolumeAutomation&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
	 *     response body
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automation updated </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public ApiResponse<VolumeAutomation> partialUpdateVolumeAutomationWithHttpInfo(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable String updateMask,
			@javax.annotation.Nullable PartialUpdateVolumeAutomationPayload partialUpdateVolumeAutomationPayload)
			throws ApiException {
		okhttp3.Call localVarCall =
				partialUpdateVolumeAutomationValidateBeforeCall(
						projectId,
						region,
						automationId,
						updateMask,
						partialUpdateVolumeAutomationPayload,
						null);
		Type localVarReturnType = new TypeToken<VolumeAutomation>() {}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * Patch volume automation (asynchronously) Partially updates a specific volume automation.
	 * Specify the fields to update in the &#x60;updateMask&#x60; query parameter.
	 *
	 * @param projectId project Id (required)
	 * @param region region (required)
	 * @param automationId automation Id (required)
	 * @param updateMask A comma-separated list of fully qualified names of fields to be updated.
	 *     Example: \&quot;name,triggers.schedule.rrule\&quot; (optional)
	 * @param partialUpdateVolumeAutomationPayload (optional)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request body
	 *     object
	 * @http.response.details
	 *     <table border="1">
	 * <caption>Response Details</caption>
	 * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
	 * <tr><td> 200 </td><td> automation updated </td><td>  -  </td></tr>
	 * <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
	 * <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
	 * <tr><td> 403 </td><td> Not found </td><td>  -  </td></tr>
	 * <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
	 * </table>
	 */
	public okhttp3.Call partialUpdateVolumeAutomationAsync(
			@javax.annotation.Nonnull String projectId,
			@javax.annotation.Nonnull String region,
			@javax.annotation.Nonnull String automationId,
			@javax.annotation.Nullable String updateMask,
			@javax.annotation.Nullable PartialUpdateVolumeAutomationPayload partialUpdateVolumeAutomationPayload,
			final ApiCallback<VolumeAutomation> _callback)
			throws ApiException {

		okhttp3.Call localVarCall =
				partialUpdateVolumeAutomationValidateBeforeCall(
						projectId,
						region,
						automationId,
						updateMask,
						partialUpdateVolumeAutomationPayload,
						_callback);
		Type localVarReturnType = new TypeToken<VolumeAutomation>() {}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}
}
