name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  main:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [11, 17, 21]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Install java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.version }}'
          cache: 'gradle'

      - name: Check code format
        run: ./gradlew spotlessCheck
      
      - name: Test
        run: make test

      - name: Build
        run: make build
      
      - name: Publish to local maven repo
        run: make install

